### ISSUE TITLE
Interesting

### ISSUE THREAD

**Issue by timozattol** [KeitIG/museeks#1]
Hey man, I'm interested, what language are you going to use ? :) 

What kind of player will it be, do you have any source of inspiration ?

:+1:

**Comment by KeitIG** [comment]
Hi Tim ! 

It will be coded in io.js (Node), and nw.js for multiplatform support. Here is a screenshot of what I have done so far, mostly test buttons ect.

![capture du 2015-03-05 10 29 52](https://cloud.githubusercontent.com/assets/1311607/6502300/957f8206-c322-11e4-90f0-725b883af6dd.png)

**Comment by timozattol** [comment]
Okay thanks for the infos! Good luck with that project :)
