### ISSUE TITLE
Reorganize main process

### ISSUE THREAD

**Issue by KeitIG** [KeitIG/museeks#104]
`main.js` is getting long, I should split this file in multiple files, with os specificity ect...

**Comment by YurySolovyov** [comment]
Does not seem to be about OS that much, rather about browser window + IPC, I can take a look.

**Comment by KeitIG** [comment]
This just should be splitted in different things: config load, ipc, os specificity... Atom has some nice approach too https://github.com/atom/atom/tree/master/
This is not urgent though.

**Comment by YurySolovyov** [comment]
It might be helpful to get right first for for #73
