### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by KeitIG** [KeitIG/museeks#116]
#FTM, only basic tests: 
- eslint
- webpack build is a big plus
- electron-packager is a plus

poke @YurySolovyov, you're ok to pick it up ?

**Comment by KeitIG** [comment]
Codeship will be used to provide CI.

**Comment by KeitIG** [comment]
Done !

**Comment by YurySolovyov** [comment]
Decided to wait until Codeship CI will support forked repos and proceeded with Travis for now

**Comment by KeitIG** [comment]
Useful links:
- https://community.codeship.com/t/github-prs-from-forked-repositories-dont-get-built/55
- https://codeship.com/documentation/faq/testing-prs-from-forked-repositories/
