### ISSUE TITLE
Using flexbox

### ISSUE THREAD

**Issue by mrzmyr** [KeitIG/museeks#12]
As from now you are using the Bootstrap 3 grid, how about using a pre existing or an own build flexbox based grid ?

**Comment by KeitIG** [comment]
Mmmh, could be interesting, but I'm using more than the grid from Bootstrap but buttons, buttons group, etc. 

It could be interesting to test performances from both grid system.

**Comment by KeitIG** [comment]
Closing it for the moment. Features are more important, and we could do that while refactoring the whole thing.
