### ISSUE TITLE
Museeks slogan

### ISSUE THREAD

**Issue by KeitIG** [KeitIG/museeks#131]
No dev here. The sentence `a free, lightweight and cross-platform music player` is great to describe shortly Museeks, but has no "personality". I'm thinking to change this to something that would sound a bit more like a slogan. ("the" instead of "a" is a great start). 

e.g: Atom is called "The hackable text editor".

**Comment by KeitIG** [comment]
I've remove the `lightweight` keyword as it's missleading: it was about user interface, but technically, the whole app is not "that' lightweight. Replaced it with "A simple, clean and cross-platform music player" ftm.

**Comment by YurySolovyov** [comment]
Just for the record, from Gitter (both by me :smile:):
- "You know, for music",
- "The shortest path to your music"

**Comment by Suriteka** [comment]
> "The shortest path to your music"

I like this one !

**Comment by YurySolovyov** [comment]
Came to me this morning: "Nothing but music"

**Comment by Phenitei** [comment]
I imagine you've already been through the usual propaganda patterns:
* "Music done right"
* "Your music's bright future"
* "Forget your dream player -- museeks is better"
* "Only for the MUSIC!"
* "You've got music!" (Read by s/music/mail/ ^^)

Or a bit more high:
"The player that'll have you squ_eek_ of excitement!"

**Comment by arnold-almeida** [comment]
I like the idea of having a hackable music player.

Customise

- Themes
- Fonts

Packages
- key analysis (similar to record box / mixed in key )

**Comment by arnold-almeida** [comment]
should also definitly make a reference to Rick & Morty

"meeseeks box" / "Mr meeseeks" etc

:)

**Comment by dkniffin** [comment]
If we decide to do #260, we should add "hackable" or "extensible" to the slogan.

**Comment by ketanhwr** [comment]
> should also definitly make a reference to Rick & Morty

"A music player that caaaaaaaaan do music!"
