### ISSUE TITLE
Better empty state

### ISSUE THREAD

**Issue by YurySolovyov** [KeitIG/museeks#132]
As mentioned in [Meet Museeks, A Stylish New Cross-Platform Music Player](http://www.omgubuntu.co.uk/2016/08/museeks-music-player-electron-app), we need to do better job meeting the user with no library updated.

**Comment by KeitIG** [comment]
:+1:

**Comment by KeitIG** [comment]
@YurySolovyov Can you test the last commit and tell me if you find that enough ?

**Comment by YurySolovyov** [comment]
It does the job, that's for sure.
I'd change some wording in general to be more friendly though.
So instead of 
```
Too bad, there is no music in your library =(
you may need to refresh your library or add folders into it.
```
we can do something along the lines of:
```
No music found yet, but that's fine, you can always [add your music in the library]
```

where the text in `[]` is a link to the library.

**Comment by KeitIG** [comment]
It would look like that
![capture du 2016-08-09 11 51 30](https://cloud.githubusercontent.com/assets/1311607/17512361/b51c0426-5e27-11e6-90ac-5232d6d37640.png)

**Comment by KeitIG** [comment]
Finished in b916d790e723bceeabba4aa522f3f15c7d54dd21
