### ISSUE TITLE
Better library updates

### ISSUE THREAD

**Issue by KeitIG** [KeitIG/museeks#135]
## What

The current problem is when refreshing the library, everything is reset, including playlists.

## How

When a file is in DB, it should not be removed with a refresh. The refresh option should not exist anymore, or should be more explicit and with a warning telling you that everything will be reset.
- [x] Add files or olders
- [x] Reset library should be more explicit (warning or danger color)
- [x] Don't freeze the interface when refreshing library
- [x] Be able to add more folders/tracks when the library is already refreshing
- [x] Add files to library by drag & dropping them on the main BrowserWindow or custom dropZone
    - [ ] Directly add files to playlist if on playlist view
- [x] Remove tracks from `TracksList` #295 
- [x] Refresh progress if footer

**Comment by YurySolovyov** [comment]
> Is "reset library" still needed ?

IMO this depends on how smart library refresh can be or how smart we want it to be.
If it is ok to wipe out current library and start over, then yeah, we can merge these actions.
One point to consider is that after hard reset users will probably want to do refresh anyway.

Building smarter refresh has some challenges - e.g. how do you handle file renames? What files are considered "same" or "equal" or "up-to-date" ... stuff like that.

**Comment by KeitIG** [comment]
The goal is to add tracks to the library when adding folders, and remove them when removing a folder. No file rename handle or whatever.

My only concern is if a track is in a playlist. Currently, a playlist looks like that:
```
// playlist
{
    name,
    type   : 'playlist',
    tracks :  [] // array of _ids
};
```

I'm ok with letting unused _ids in playlists, as they won't be fetched by NeDB anyway, and it's hard to look for them.

OR

change data structure and do sth like: 
```
{
    _id,
    name,
    type   : 'playlist',
}
```

and another collections to join them: 
```
{
    trackId
    playlistId,
    order
}
```

which looks a bit more like SQL

**Comment by KeitIG** [comment]
This is not a problem with an `order` key and/or an unique _id

**Comment by YurySolovyov** [comment]
> The goal is to add tracks to the library when adding folders

This makes a lot of sense, we can also put refresh buttons on individual folder items, and drop refresh/reset buttons completely

**Comment by YurySolovyov** [comment]
An idea: maybe as part of this effort, let's move library management view to a separate tab at the bottom? I don't really feel it belongs to settings...

**Comment by dkniffin** [comment]
Wow, I didn't realize how much of a pain this is until I got some new music. I tried doing a refresh, it froze (or took forever, not sure), so I deleted the `museeks` config dir, and now I'm doing a fresh db import, and it's taken hours so far. Not sure if something's changed, but I don't remember it being this painfully slow the first time I did the import.

**Comment by KeitIG** [comment]
@dkniffin this bug is fixed in the branch of this current issue. You'll need to delete the conf folder again though.

**Comment by KeitIG** [comment]
God I really need to finish this.

**Comment by dkniffin** [comment]
Oh wow! Yea, that fixed it. It finished in a matter of minutes, instead of hours. We should definitely get this merged soon.

**Comment by sabrehagen** [comment]
Yep, please merge!
