### ISSUE TITLE
Missing .desktop file.

### ISSUE THREAD

**Issue by Pival81** [KeitIG/museeks#138]
Hi, i tried to make a package for archlinux, it works (i basically put everything in /opt/museeks and made a symlink to /usr/bin)  and i want to upload it on the aur, but a .desktop file to launch it from the desktop is missing, could you please provide it so i can make a proper package for the aur?

**Comment by KeitIG** [comment]
Hey @Pival81 !

Should not be too hard, should it be placed at the root of the package ?

**Comment by Pival81** [comment]
What do you mean "root of the package"?

**Comment by KeitIG** [comment]
I meant the root of the project. I'm not an expert in .desktop files, basically, it should look like this right ?

```
[Desktop Entry]
Version=0.6.0
Name=Museeks
Comment=a free, lightweight and cross-platform music player
Exec=/opt/museeks/museeks
Icon=/opt/museeks/resources/app/src/images/logos/museeks.png
Terminal=false
Type=Application
Categories=Music;Audio;
```

**Comment by Pival81** [comment]
It's good (i think), i'll try it once i get home.
If it works, i add it to the package and upload it to the AUR.

**Comment by KeitIG** [comment]
I'll add this file to the project soon

**Comment by Pival81** [comment]
Before you do the next release, i'll have to add it as a second file along with the main archive.

**Comment by KeitIG** [comment]
Related issue #100 : create app installers

===

If you want to maintain Museeks on AUR, I can't give you any "official" support, that means you'll have to maintain the package manually for now.

Our short-term goal target is to package a .deb and a .tar.gz. Maintaining AUR or a PPA is not really whised. As I have no time for this, and there are important features to implement first.

**Comment by Pival81** [comment]
Of course, i'll care about the AUR package.

**Comment by KeitIG** [comment]
Ok, so let's sum it up, the .desktop file must be at the root of the .tar.gz (in the same directory as the ./museeks excutable) right ?

- [ ] Add a system in `build.js` to add some files at the root of the package depending of the targeted os

**Comment by Pival81** [comment]
It's better if it's placed at the root of the archive, yes.
It should be:
tar -zxvf archive.tar.gz 
cd archive 
sudo cp -R * /opt/museeks 
sudo ln -s /opt/museeks/museeks /usr/bin/museeks 
sudo cp /opt/museeks/museeks.desktop /usr/share/applications/museeks.desktop

**Comment by Pival81** [comment]
But consider that the package is yet up and eunning on the AUR.
You just need to add the desktop file to the repo.
Now, i just noticed that another user made another package "museeks-bin", 3 hours before me.
It is essentially the same package, only the name changes.
And, that first line in the .desktop file (#!/usr/bin/env xdg-open) it's useless, you can delete it.

**Comment by KeitIG** [comment]
Ok thanks for all the informations, I will push an update of the build script that automatically include a .desktop file for linux builds.

(poke #100)

**Comment by palob** [comment]
Please install the icon a location compliant with [freedesktop.org standards](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html).

``/usr/share/pixmaps``
``/usr/share/icons/hicolor/[size]/apps``
``~/.local/share/icons/hicolor/[size]/apps``

You can change the icon line in the ``.desktop`` launcher to just ``Icon=museeks`` then.
Cf. this [example ``.desktop`` launcher](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#example) presented in the freedesktop.org documentation.

This allows for icon theming. Furthermore you can provide different icons in the various ``.../hicolor/[size]`` directories (in case you've got distinctly designed icons for different sizes).

The system will choose the appropriate size automatically.

**Comment by KeitIG** [comment]
Some news.

Installers are our main focus for 0.8. We will have to rewrite a part of our build system to integrate a .desktop, but this should come with the next release :)

**Comment by KeitIG** [comment]
Shouldn't be needed anymore now .deb, snap and appimages are here.
