### ISSUE TITLE
Library Sync Support

### ISSUE THREAD

**Issue by kellertobi91** [KeitIG/museeks#143]
What would be really nice is to have some kind of Synchronisation of the Music Library between multiple Computers, e.g. a Desktop and a Laptop.

**Comment by KeitIG** [comment]
You mean to share the same library across devices or to do a real Sync like Dropbox ?

**Comment by kellertobi91** [comment]
Well, a real Synchronisation would be great, but I would be fine, if the library would be managable with e.g. git.

What also would be great is if I could say, that I want to "share" a part of the library e.g. a set of playlists and then create a one-way-sync to e.g. google drive or dropbox for that (with the subset of the library file as well as m3u-playlists) that would make that player as powerful as iTunes.

I once have written something like the following for banshee:

- Export a selected subset of playlists as well as the necessary files for those lists
- hardlink the music files in a separate folder with changed foldernames that are ascii-proof (e.g. some kind of hash) - this saves disk space and prevents character encoding problems in filenames
- generate m3u files
- sync this folder with google drive to my smartphone, laptop and office pc

the only problem with this is, that there is no good player for linux that works like poweramp or gonemad player on android (reading the m3u and acting as if there were a library - but on change of the playlist files change the playlists in the player)

So what I would suggest is the following:

- having a solution like the one described above as a plugin or as a core of museeks
- being able to create a subset of the library that will also be synced with google drive
- being able to define multiple of such sync-sets
- AND (and here comes the thing that makes it more powerful than itunes sync): If something changes in the subset, write a changelog and as soon as we sync again with the main library, we show what changed and ask the maintainer of the main music library if they want to "commit"/"merge" the changes


This would be a great use for:

- Users who like ordered playlists that have a special theme or "musical flow" and work on multiple computers
- Families and or Cummunities who share a common music library and everyone decides what music they want to carry
- dancing schools with a central music library and teachers can tell "No, this is not a tango"

**Comment by YurySolovyov** [comment]
To be honest, I feel like this is out of scope for museeks,
While I can see how this can be nice-to-have build-in, I think you can achieve same thing with some mature sync solution and run museeks against synced directories.

**Comment by kellertobi91** [comment]
Hmm, was just an idea
If the files are relative in the library and the library has an easy to read format, I could use git for this probably.

**Comment by YurySolovyov** [comment]
DB is stored in user's folder, look for `library.db`

**Comment by kellertobi91** [comment]
Ok, then weather the "playcount" needs to be rendered in a new line or disableable, otherwise it would not work with git, because the count could change on both "branches" and I think manual merges are not nice for that big music libraries.

**Comment by KeitIG** [comment]
I keep the idea of sharing a library across multiple computers. But it a really low priority compared to the 1.0 milestone. Maybe in a 2.x ?

**Comment by YurySolovyov** [comment]
If the idea is to sync library only, I don't get how is it useful.
If the idea is to sync both library and actual files, I still think this is out of scope.

In any case, from my experience, any kind of synchronization requires user to have some kind of identity, which implies either building our own service, or use 3rd party ones. This would require embedding some kind of client into the app that manages sync concerns.

I still think that if you want to have your music accessible from everywhere, just use one of cloud storage solutions or even spin up your own cloud, they often have some notion of synced folders or similar concept.

I wonder what is the minimal set up for embedding say, dropbox client for syncing...

**Comment by KeitIG** [comment]
My music is on my Windows partition, and I can access it easily from Linux. It could be the same with Dropdox: just sync your files with the Dropdox client, then load them as Yury said.

When Museeks will be used by 1 million people (I like dreams), we can investigate solutions for that.

Closing it :)
