### ISSUE TITLE
Usability: Better Workflow for Starters

### ISSUE THREAD

**Issue by kellertobi91** [KeitIG/museeks#144]
I had to click around a bit to figure out how to get my music inside. I missed out the "Refresh Library" button.

I would love to see the following:

- a link to the settings on the "No Tracks found" page when the app is startet the first time
- when added folders the first time and leaving settings a warning like "Don't you want to refresh the library?"

**Comment by KeitIG** [comment]
Hey ! Thanks for the tips.

It has partially already been done (!) :) 

e84c9e637930f749cd71ee23a8d370a12d9fd56a
b916d790e723bceeabba4aa522f3f15c7d54dd21

See the screens here (the first one): https://github.com/KeitIG/museeks/issues/132#issuecomment-238506936

It will be released soon (today or tomorrow).

For the library refresh thing, the workflow will change soon, see #135

**Comment by KeitIG** [comment]
It's been released !
