### ISSUE TITLE
Contributors list update

### ISSUE THREAD

**Issue by KeitIG** [KeitIG/museeks#147]
I'll remove the contributors list in 0.7.0. Because it's not easily maintainable.

A new one will probably appear on the website, waiting for https://github.com/KeitIG/museeks.io/issues/2

- [x] Remove contributors list
- [x] Add a link to the new contributors list on museeks.io

**Comment by YurySolovyov** [comment]
Good idea. Site is much better place for such stuff.

**Comment by KeitIG** [comment]
Done. There's a small list on museeks.io. It's not finished but it does the job for now.
