### ISSUE TITLE
Make an option to run Museeks with native frame

### ISSUE THREAD

**Issue by KeitIG** [KeitIG/museeks#153]
This would help to get minimize/maximize etc... (#41), the time we unblock the situation. In this case, remove the "close button"

- [x] Option "use native frame" in settings
- [x] Hide controls if this is checked
- [x] auto-restart the app ?

My only concern is with the dark theme on some Linux environments (libchromium being build with GTK2):

![capture du 2016-08-16 17 30 11](https://cloud.githubusercontent.com/assets/1311607/17705031/3dc86422-63d7-11e6-985e-afd2293d2c57.png)
![capture du 2016-08-16 17 30 25](https://cloud.githubusercontent.com/assets/1311607/17705030/3dc0ed0a-63d7-11e6-8de1-570359f9bb02.png)

**Comment by YurySolovyov** [comment]
Here is the idea: make header render differenly depending on OS.

Render Windows-like buttons on the right for Windows:
![image](https://cloud.githubusercontent.com/assets/2168518/17715140/877e9760-640b-11e6-8338-3d34d8ade2b5.png)

Render OS X-like buttons on macOS:
![image](https://cloud.githubusercontent.com/assets/2168518/17715151/97b94d64-640b-11e6-8378-2b7f29f9912e.png)

Render some generic buttons on Linux: Same as today + minimize and maximize buttons
