### ISSUE TITLE
Split Sass in multiple files

### ISSUE THREAD

**Issue by KeitIG** [KeitIG/museeks#16]
- Split styles in multiple files (see Webpack behavior with that)
- Use variables for colors
- ... bla

and all that stuff. Use SCSS just for nesting is ridiculous.

**Comment by mrzmyr** [comment]
It would also be cool to make components out of the "one big file".

**Comment by KeitIG** [comment]
Indeed !

**Comment by mrzmyr** [comment]
Thats also a reason why I was preparing the components in the BEM methodology, that way its easier to move them to components.

**Comment by KeitIG** [comment]
Still not the most urgent thing to do. One great thingwould be to compile SASS on the fly. A bit like Atom. This would make theme integration less dirty for example.

**Comment by puranjayjain** [comment]
@KeitIG wouldn't it be easier to just switch to less and use less.js on the fly? Just a consideration (I'll be ready to help if a PR is needed :smile: )

**Comment by KeitIG** [comment]
@puranjayjain Yes it would ! I was thinking about  that but I didn't really investigateurs how to do that. Feel free to submit a PR for that ❤

**Comment by KeitIG** [comment]
Done in 97e6b8be2d4a7b651555b71eea1f48422d5e2067
