### ISSUE TITLE
Implement track playCount incrementation

### ISSUE THREAD

**Issue by KeitIG** [KeitIG/museeks#160]
There is a field for `{ type : 'tracks' }` called `playCount`. It would need to be incremented when needed. 

Will be used for: #62 
- [x] should it be incremented on `ended` event or when starting a track ?
- [ ] do it

**Comment by cfollet** [comment]
If we take for example the [apple's policy on the subject](http://apple.stackexchange.com/questions/6675/what-does-plays-really-count-in-itunes), they **increment** play count **at the end** of the track. Not strict end but maybe `totalTime - delta`.
I think increment playCount at the strict end would be a bad idea. If we use fading in the future or even if we change track after listening almost all a song.

So I am guessing at the middle or at totalTime - delta. What do you think?

**Comment by KeitIG** [comment]
I think it's a good idea, even if harder to implement. I'd say a delta in a certain percentage of the total duration would be better than a fixed value.

One problem is: "what happens if we seek back in a track.currentTime, then the delta is reached again ?"

**Comment by YurySolovyov** [comment]
I think youtube treats views at the beginning, and it much easier to implement.

**Comment by KeitIG** [comment]
I'm not sure Youtube considers a video completely seen as soon as you start watching it

**Comment by cfollet** [comment]
@YurySolovyov If by beginning you mean when a song starts, I am against. When you are skipping songs while searching for one, it will readCount +1 foreach song passed/not listened.

**Comment by YurySolovyov** [comment]
@cfollet yeah, valid point, so I guess if we are talking about some threshold anyway, I'd say it should be at the end.
> One problem is: "what happens if we seek back in a track.currentTime, then the delta is reached again ?"

Well, since this feature is for users that need such info, I don't think they would clutter their own statistics on purpose. This might be just the first iteration of this feature, and we can add an ability to (re)set play count later on.
