### ISSUE TITLE
Look for covers in track's directory

### ISSUE THREAD

**Issue by YurySolovyov** [KeitIG/museeks#166]
Tracking issue for making museeks look into track's directory for album cover art.

Questions to resolve
- [ ] what if track added from directory with >1 image there?
- [ ] what filenames to lookup ? all or just `/(cover|album|whatever).(jpg|png|bmp)/i` ?

Refs: #86

**Comment by KeitIG** [comment]
Excellent Idea.

**Comment by KeitIG** [comment]
Adding the 0.7.0 milestone. Waiting for #191 's first tasks to be done though.
