### ISSUE TITLE
Improve development UX

### ISSUE THREAD

**Issue by YurySolovyov** [KeitIG/museeks#169]
Even on my home 4c/8t Xeon machine with 16GB of RAM webpack takes ages to build.
We should take a look at [webpack docs](http://webpack.github.io/docs/build-performance.html) and make sure we're getting comfortable build times and overall UX, otherwise report issues to webpack or babel.

**Comment by KeitIG** [comment]
a webpack build takes around me 5/10 seconds for me. With a quite powerful laptop.

**Comment by dkniffin** [comment]
I'm also getting this issue. It takes about 30 seconds per build on my machine (Macbook Pro from 2015, with 2.2GHz i7, 16GB ram). 

Most of the time is spent on `78% additional chunk assets`. I spent a little while trying to track down what is causing that. The only thing I found was [this](https://github.com/webpack/webpack/issues/537). One solution pointed to UglifyJS, which we're not using, but I'm not familiar enough with this project to know whether any of the other suggestions apply.

I wonder if it would make sense to not use the minified version of everything when running in development?

**Comment by KeitIG** [comment]
Thanks for the report of the upstream issue, I'll get a look at it more deeply soon.

**Comment by YurySolovyov** [comment]
Note: we might want to disable minification when running in dev mode

**Comment by KeitIG** [comment]
And build source maps too

**Comment by YurySolovyov** [comment]
@KeitIG when I started `eion` in js first, I used `webpack-dev-server` to serve assets (it is faster).
To do so, I did something like that in index.html file:
```html
<script defer>
  (function() {
    const dev = process.env.ENV === 'dev';
    const script = document.createElement('script');
    script.src = dev ? 'http://localhost:9090/dist/app.js' : 'app.js';
    script.defer = true;
    document.head.appendChild(script);
    
    const styles = document.createElement('link');
    styles.rel = "stylesheet";
    styles.href = dev ? 'http://localhost:9090/dist/style.css' : 'style.css';
    document.head.appendChild(styles);
  }());
</script>
```

Are you ok with this for museeks?

**Comment by KeitIG** [comment]
@YurySolovyov Do we consider it as done or you want to talk about dev-server ?

**Comment by YurySolovyov** [comment]
I'd give it a try at least.

**Comment by KeitIG** [comment]
What does it change compared to the current build system ?

**Comment by YurySolovyov** [comment]
1. Adds `publicPath: 'http://localhost:9090/dist/'` to `webpack.config.js`
2. Need to somehow start dev server. 
    ```js
    'use strict';
    const express = require('express');
    const webpack = require('webpack');
    const webpackDevMiddleware = require('webpack-dev-middleware');
    const config = require('./webpack.config');
    const compiler = webpack(config);
    const app = express();
    app.use(webpackDevMiddleware(compiler, {
     publicPath: config.output.publicPath,
     stats: {
       colors: true
     }
    }));
    app.listen(9090);
    ```
3. Snippet I posted above for `index.html`

Just writing this, I realized that this is for `webpack-dev-middleware`, `webpack-dev-server` might be much easier to set up.

I'll investigate and post results here.

**Comment by KeitIG** [comment]
I mean, what does it do ?

**Comment by YurySolovyov** [comment]
It keeps bundle in memory and recompiles it on change.
Can't say anything about how faster it feels, still need to investigate.

**Comment by KeitIG** [comment]
Ok, so the bundle is in memory and not in a file, I'll do some researches about how useful it can be.

**Comment by KeitIG** [comment]
Ok, it seems like it's useful only if we use react-hot-loader, I may be wrong though

**Comment by YurySolovyov** [comment]
It is required for `react-hot-loader`, but should be useful without it too.

**Comment by KeitIG** [comment]
I still see no difference between `webpack --watch` and dev-server, if you find any useful information, I'd be curious to know them.

Some refs:

- https://webpack.github.io/docs/webpack-dev-server.html

**Comment by YurySolovyov** [comment]
@KeitIG See the list at the top https://webpack.github.io/docs/build-performance.html

**Comment by dkniffin** [comment]
I'm not 100% sure how webpack-dev-server fits into electron development, but the goal would be to get hot reloading to work. So, if you change any of the views, the main window is updated to reflect that, without restarting or anything.

**Comment by KeitIG** [comment]
That's my point, if we can get hot-loader working, why not, otherwise, perfs are good enough I have to say.

**Comment by KeitIG** [comment]
Build times are satisfying. HMR not there yet, maybe later in a separate issue.
