### ISSUE TITLE
Deal with large databases

### ISSUE THREAD

**Issue by KeitIG** [KeitIG/museeks#173]
NeDB fails with large database (e.g >300mb). https://github.com/louischatriot/nedb/issues/442

This was mainly introduced with #165 

We have a few options (multiple can be selected):
- Remove covers from database
- Change database (a real mongoDB, [linvodb3](https://github.com/Ivshti/linvodb3) ?)

### LinvoDB3

- [x] Switch to Linvo + leveljs
- [x] Use different models for tracks and playlists
- [x] Create schemas for each models
- [x] Edit TroubleShooting in Readme

some points with linvo:
- Storing covers in Library slows down things "a lot"

**Comment by YurySolovyov** [comment]
LinvoDB looks nicer indeed, even without solving this particular issue

**Comment by KeitIG** [comment]
LinvoDB came up after I implemented NeDB. I'll need to investigate a bit more about it, it indeed looks nice.

Of course it's one option amongst others.

**Comment by YurySolovyov** [comment]
From gitter:
```
Yury @YurySolovyov 15:17
well, I purpose not to store them at all

Pierre de la Martinière @KeitIG 15:19
you mean only to use local jpg ?

Yury @YurySolovyov 15:19
I mean make an express service on main process
that would handle requests for the covers and make cover component a simple img tag
for now this service would do same thing - using musicmetadata to get the image
later it would be easier to extend it to look into track folder
and even later we may add a way to look it up in the internet
I know I'm kind of pushing, but I think this solution would scale better
in terms of complexity
this could be done by registering new protocol, say, cover://
so the image source would be just cover://<filepath>

Yury @YurySolovyov 15:25
I can do later since library size is not same as app crash,
but I think this approach is better
```

**Comment by YurySolovyov** [comment]
This way covers are fetched only when they needed, which is probably slower in raw numbers, but still low enough to be comfortable to users

**Comment by YurySolovyov** [comment]
One concern about LinvoDB: can we use it in main process?
