### ISSUE TITLE
Better media keys support + fix not working ones

### ISSUE THREAD

**Issue by YurySolovyov** [KeitIG/museeks#176]
Electron can listen for [`globalShortcut`](http://electron.atom.io/docs/api/global-shortcut/)s via following [`Accelerator`](http://electron.atom.io/docs/api/accelerator/)s:
- MediaNextTrack, MediaPreviousTrack, MediaStop and MediaPlayPause
- VolumeUp, VolumeDown and VolumeMute

Let's use that.

**Comment by KeitIG** [comment]
Hem.

https://github.com/KeitIG/museeks/blob/master/src/js/actions/AppActions.js#L121

**Comment by YurySolovyov** [comment]
@KeitIG fair, volume still remains :)

**Comment by KeitIG** [comment]
@Suriteka said the play/pause mac keyboard button was working, but not the next/prev, can you confirm that Jonathan ?

**Comment by Suriteka** [comment]
@KeitIG Nop the Play/Pause don't work, just the Next and Previous works perfectly.

**Comment by KeitIG** [comment]
ah ok, thanks I'll investigate

**Comment by KeitIG** [comment]
@Suriteka @YurySolovyov 

I remember why I did not implement volume global shortcut: managing volume from the app does not make any sense, as if you toggle the mute key, it'll mute all your laptop, so no need to mute Museeks too. Same for `volume-up` and `volume-down`

**Comment by YurySolovyov** [comment]
Ah, makes sense, well, at least you found the bug :)

**Comment by KeitIG** [comment]
Done.
