### ISSUE TITLE
Deal with exceptions and errors

### ISSUE THREAD

**Issue by KeitIG** [KeitIG/museeks#178]
An error/exception should not - if possible - block the UI. Or there should be at least a UI feedback with a notification, like in Atom.

Options:
- `try`/`catch` everywhere
- `window.onerror`
- I think Electron has something for that, but I don't remember well where

**Comment by YurySolovyov** [comment]
One thing is how to make them unobtrusive so that if throws many times it would annoy users quickly

**Comment by cfollet** [comment]
Also make  sure, if we use `try / catch`, that they aren'tinside performance-critical functions.

**Comment by KeitIG** [comment]
Fixed with an error boundary in 1c9395a

![screen shot 2018-08-20 at 01 41 42](https://user-images.githubusercontent.com/1311607/44314509-61b29a80-a41a-11e8-8944-9aeb069bad53.png)
