### ISSUE TITLE
Support for Macbook keyboard media buttons

### ISSUE THREAD

**Issue by valdotdev** [KeitIG/museeks#185]
Please support media playback control using the media buttons of Mac keyboards.

**Comment by YurySolovyov** [comment]
So, I guess you tried it and it is not working? Do you see any errors in console in dev mode? /cc @KeitIG

**Comment by KeitIG** [comment]
Hello ! It has been done here: https://github.com/KeitIG/museeks/pull/177

It will be released as soon as we complete the 0.7.0 milestone :)

**Comment by valdotdev** [comment]
Apparently since I also installed Vox and Vox preferences, it's taking ownership of the buttons so that's why it wasn't working. @YurySolovyov I assumed it wasn't supported yet since it didn't work the first time hence me filing this issue.
