### ISSUE TITLE
InputActions or something ftw

### ISSUE THREAD

**Issue by KeitIG** [KeitIG/museeks#190]
This could really help the UX to have someting like in Atom where you can input a text. For example a playlist name.

The name is bad though :p

![capture du 2016-08-29 11 08 06](https://cloud.githubusercontent.com/assets/1311607/18046599/e2a32a8a-6dd8-11e6-8b5a-f99663c5cd77.png)

**Comment by YurySolovyov** [comment]
I think this is genrally called Commands

**Comment by KeitIG** [comment]
It's not exactly loke the palette, it's really just an input.

Basically, it should be something we can call with a single function that returns to us the given string.

**Comment by YurySolovyov** [comment]
I'm mot sure how well it fits to media application like museeks, in Atom, it makes sense because most interactions are done via keyboard, and since we already have media keys working, I'm not sure how much value this can add.

**Comment by KeitIG** [comment]
It would be to reduce number of interactions to create/edit playlists. It's some minor UX improvements.

I'm closing it and will re-open it if other use-cases appear.

**Comment by YurySolovyov** [comment]
> It would be to reduce number of interactions to create/edit playlists

This is the actual problem then: too many interactions required for playlists.

**Comment by KeitIG** [comment]
It is the "upper problem" indeed, but it's low priority.
