### ISSUE TITLE
Decent cover support

### ISSUE THREAD

**Issue by KeitIG** [KeitIG/museeks#191]
## Why

- Light cover support (#86) was ok, but definetly not scalable.
- #173 helped us to deal with large database, but the library loading is extremly long.

This issue is here to make things decent.

## What

- [x] Redefine tracks's cover schema
- [x] Do not store covers in base64 for each track (new collection, create images or look for them on the fly)
- [x] Look for covers in track directory #166 

## How

In my mind I have something like:

``` js
{ // track without any cover
    cover: null
},
{ // another track with a cover in its id3 tags
    type: 'id3',
    data: 'aCoverIdOrAbase64StringOrSthToBeDefined'
},
{ // another track with a cover.jpg in his directory
    type: 'file'
    data: 'filepath'
}
```

@YurySolovyov emmited the idea of an internal server serving them.

**Comment by YurySolovyov** [comment]
Can our new db do joins?

**Comment by KeitIG** [comment]
NoSQL cannot do joins. We have to fetch data manually.

**Comment by YurySolovyov** [comment]
I purposed media server idea once, but it did not found you support :)

**Comment by KeitIG** [comment]
It's in the desc ;) 

Basically, you would create an api "getCover" if I get it correctly ? And it would be called every time a track is played ?

**Comment by YurySolovyov** [comment]
Yeah, the idea is to decouple cover image retrieval from actual underlying mechanism so that cover component only sets image `src` and does not care about how cover was fetched.
