### ISSUE TITLE
M4A files are not seekable

### ISSUE THREAD

**Issue by valdotdev** [KeitIG/museeks#193]
Didn't test on other file formats but I noticed when playing *.m4a audio files, they're playable but not seekable whatsoever. It starts over when trying to seek/clicking on the bar. Specifically, these files were taken from YouTube videos using youtube-dl. Not sure if any other m4a files work.

OSX 10.11.6

**Comment by KeitIG** [comment]
Do you have a file to send me ? (see my email adress on my profile)

**Comment by valdotdev** [comment]
Sample file sent ;)

**Comment by KeitIG** [comment]
On Linux it's working fine with `master`, you're using 0.6.3 right ? 

Can you open the dev tools and tell me if you see an error ? (settings -> advanced -> dev mode)

**Comment by KeitIG** [comment]
@valdotdev I've identified the bug. It's because the file has 00:00 duration due to an old bug (#103).

It was fixed a few days ago and will be released as soon as we've finished the work on 0.7.0 issues :) (https://github.com/KeitIG/museeks/milestone/10)

**Comment by valdotdev** [comment]
@KeitIG Oh great, that's good. :) I was about to post the log
Here it is anyway `An error occured while reading /Users/Val/Music/untitled folder 2/wally's blues acoustic.m4a id3 tags: Error: Could not find metadata header`
