### ISSUE TITLE
Easy access to an artist/album

### ISSUE THREAD

**Issue by KeitIG** [KeitIG/museeks#198]
Following #196

Instead of a direct link, I think it should be in a contextual menu when right-clicking on a track:

- ...
- Play next 
- _____
- Go to...
    - artist
    - album
-  _____
- Add to playlist

**Comment by cfollet** [comment]
And by clicking for example to :` Go to Artist`, It will fill the search input with the artist of the selected song?

**Comment by KeitIG** [comment]
It's the idea yes. Then it will trigger a filter search.

The only limitation is that if you click on "Go to The Do", it will show the tracks of The Door too. So we may need to be more specific: instead of `Go to "The Do"`, maybe we should use `Search for "The Do"`

**Comment by YurySolovyov** [comment]
Maybe it is a separate issue, but IMO you should be able to choose the field you are searching by.

**Comment by KeitIG** [comment]
/all Which is your pref ? (poke UX man @Suriteka)

![m2](https://cloud.githubusercontent.com/assets/1311607/18306010/3891e7e8-74ea-11e6-87e2-62ceb253b7c0.png)
![m](https://cloud.githubusercontent.com/assets/1311607/18306011/38931c76-74ea-11e6-93ef-aa415f95dd64.png)

@YurySolovyov It's indeed a new user story.

**Comment by YurySolovyov** [comment]
I like the first one cause it does not pollute context menu that much, but second one requires less interactions, I can't decide :sob:

**Comment by KeitIG** [comment]
I think the second one is a bit more practical. Let's wait for other's comments.

**Comment by KouKroute** [comment]
Hi people, I'm trying your fine soft (Win10 x64) and i love the way it goes. So I wanna help you find some ideas to enhance this wonderfull project. I'm a Winamp user, and now i want something more like Museeks ! So let's go on this issue :

Maybe you should do just like win10 Groove. This software is not the best, but you can click on the artist/album to show more information. On the screenshots, I just clicked on the album then Groove get me on the album, as you wanna do with a right click and a context menu. I don't think this is the best way to simplify the software.

![groove](https://cloud.githubusercontent.com/assets/22055523/18317442/910f1a62-74f4-11e6-8de6-4120cf340e57.JPG)

![groove2](https://cloud.githubusercontent.com/assets/22055523/18317441/910d0308-74f4-11e6-94af-72be0086317f.JPG)

:)

PS: if you don't need my advices, I won't bother you anymore (i'm not a coder, but a fanboy ^^)

**Comment by KeitIG** [comment]
@KouKroute first rule: all advices are welcome ! (even If I'm the boss, it's an open-source project :p)

So basically, with only a left click on the album/artist, you go to the current album/artist ?

**Comment by KouKroute** [comment]
Thanks KeitIG :)

Yeah that's it. And i found it really usefull in MS Groove (!) - and really light to use. You are going the same way, but with context menu : more clicks, and more things to show up.

**Comment by YurySolovyov** [comment]
@KeitIG how about turning `album` and `artist` cells text into clickable links that perform search?

**Comment by cfollet** [comment]
I will prefer this solution @YurySolovyov. 
It require less interactions and can be extended for a large range of clickable ID3 tags. If we do this using menu, we will end up having really long menus. We can just make the hovered link underlined for example.

**Comment by YurySolovyov** [comment]
@cfollet one downside of that solution is that it may introduce some accidental clicks, so that UX can be worse. This should be solvable, just not sure how yet.

**Comment by cfollet** [comment]
@YurySolovyov By using Ctrl + Click (like in eclipse go-to) / Double Click? or it will not be user friendly?

**Comment by YurySolovyov** [comment]
@cfollet not really discoverable by users, how would they know about that?

**Comment by YurySolovyov** [comment]
I don't really consider accidental clicks possibility as blocker, just a thing to be aware of.

**Comment by KeitIG** [comment]
Yury pointed out the main problem: how to distinguish doubleclick and click on a track for example ?

Groove doesn't let you multi-select tracks right ? I'll test it tonight to see how they deal with that.

(Meanwhile, continue to discuss about that, every opinion is welcome)

**Comment by YurySolovyov** [comment]
How about adding an icon after text that shows up on hover, and clicking that icon does the job?

**Comment by commondream** [comment]
I like the right click menu solution, and I like the direct link idea (seems I've seen that somewhere!). I think @YurySolovyov's idea of showing an icon is smart too - though - hover shows a little search icon, and you click it to focus search.

It would be very ideal to have the search only pull albums or artists that match, though, instead of all fields like search currently does. I have a lot of albums with names that match other albums.

**Comment by KeitIG** [comment]
I've had a look at how Groove is implementing it. It's indeed a direct click on the artist/album. It makes sense with Groove because every track row has an important padding, but Museeks has thin track rows.

**Comment by KeitIG** [comment]
Let's go with the right-click solution for now. It may be changed in the future.

I used a hack to update the search input, if anyone comes with a better solution, he's welcome.
See https://github.com/KeitIG/museeks/commit/a952564861350915393363867348de17f4673ef0#diff-b51d1f0783a7035655dd73df4799f325R170

**Comment by KeitIG** [comment]
Done in #206
