### ISSUE TITLE
How to: Update ubuntu gnome

### ISSUE THREAD

**Issue by esarandon** [KeitIG/museeks#199]
I am ussing Museek 0.6.0 and I want to update to the new 0.6.3.
When I click on chek for update it says that I have to go to your website. 
How do I do the update? I download the new version, delete old one and install new one? or there is another way to just update?

**Comment by KeitIG** [comment]
Hello, 

Museeks has only portable versions for the moment. This means that there is no installation required and you can have the app in different folders. Just delete your old Museeks folders and replace it by the new one.

There can be some database changes across versions, so you may need to refresh your library after an update.
