### ISSUE TITLE
Support play/pause/rwd/fwd keys

### ISSUE THREAD

**Issue by KouKroute** [KeitIG/museeks#200]
Hello people !

Would it be possible in the future to implement support of keyboards play/pause (and others) buttons ?

**Comment by YurySolovyov** [comment]
Hi.
It should be fixed in [0.7](https://github.com/KeitIG/museeks/releases/tag/untagged-d12d585e32e112d94c27).
Please use search, thanks.

**Comment by KeitIG** [comment]
Hello ! As Yury said it "should" be fixed in 0.7.0 (will be out in a few days). However, we'll need a confirmation, so don't hesitate to post a new message if something goes wrong :)
