### ISSUE TITLE
Native notification API

### ISSUE THREAD

**Issue by KeitIG** [KeitIG/museeks#202]
Add a simple native notifications support, even if not used for now. (AppActions.NativeNotifications ?)

ref: http://electron.atom.io/docs/tutorial/desktop-environment-integration/#notifications-windows-linux-macos

**Comment by YurySolovyov** [comment]
How about migrating all notifications to use native ones?

**Comment by KeitIG** [comment]
I've thought about this, but we don't need global notifications for everything. They can be useful for 

- when the database refresh is finished
- when a new track is played
- ...

They are not useful when:
- an audio error happens
- tracks are added to a playlist ...
- ...

We can imagine a silent mode for global notifications too (disable them).

**Comment by KeitIG** [comment]
I think we could rename current `AppActions.Notifications` by `AppActions.Toasts`, and use `AppActions.Notifications` for desktop notifs

**Comment by YurySolovyov** [comment]
Whatever we come up with, it shouldn't be both native and current ones. We should pick one.

**Comment by vprigent** [comment]
I was thinking about this feature. Shouldn't we keep the two features and when accessible ( Windows 10, some Linux distros, OSX ) use the native notifications, otherwise, use the toasts ?

Because, if i'm not mistaken, Windows 7 and some Linux distros does not have a built-in notification service ?

**Comment by YurySolovyov** [comment]
@vprigent Windows7 has baloons.

**Comment by vprigent** [comment]
IMO Balloons is not completely notifications. It induce that the app is always on the tray.

**Comment by YurySolovyov** [comment]
Well, it is what electron uses on Windows7, just saying.

**Comment by KeitIG** [comment]
Linux and Win32 (>Windows 8) do have native notifications

**Comment by dkniffin** [comment]
I think this is the next thing I want to tackle. I think #264 laid most of the groundwork. I'll assign myself to it.

**Comment by KeitIG** [comment]
Todo-list is above in the comments

**Comment by dkniffin** [comment]
Regarding balloons on windows 7:

> On Windows 7, notifications are not supported. You can however send "balloon notifications" using the Tray API.

**Comment by KeitIG** [comment]
If you feel brave enough to provide a fallback for Windows 7... ;)

**Comment by dkniffin** [comment]
Hmm, I'm not sure if we want to do that. From my experience, those balloons tend to be very annoying. In my mind, they're associated with java updates, and other annoying pop-overs. I think we should wait and see if it's something people want.

**Comment by KeitIG** [comment]
> they're associated with java updates

Holy baguette...

**Comment by dkniffin** [comment]
Just balloons. I think the native windows 8/10 and OSX notifications are still useful. In fact, I've been missing them a lot since switching to Museeks, which is why I wanted to tackle this :P

**Comment by KeitIG** [comment]
Btw @dkniffin what are the kind of usecases where you would expect to receive a notification ?

**Comment by KeitIG** [comment]
Just asking, because maybe they can be done in this issue too

**Comment by dkniffin** [comment]
I was just thinking song start. Coming from other players, it's useful when a song starts to get a quick pop-up with metadata for the new song.

**Comment by KeitIG** [comment]
I was thinking about that too, with the album cover it'd be even better

**Comment by dkniffin** [comment]
Yea, in my head I'm picturing this:

<img width="357" alt="screen shot 2016-11-29 at 9 44 11 am" src="https://cloud.githubusercontent.com/assets/1680080/20713993/734b17a0-b618-11e6-94a1-a423d23416f0.png">

**Comment by YurySolovyov** [comment]
I wonder how much if an effort would be to add several levels of notifications, so I can see when an update is available, but not when the new song starts

**Comment by dkniffin** [comment]
Aka: a user setting for disabling certain notifications? I think that'd be easy enough.

**Comment by YurySolovyov** [comment]
yes, something like that, I just wonder how to make it look/feel nice

**Comment by KeitIG** [comment]
We can add options in settings in another issue if needed

**Comment by dkniffin** [comment]
Alright, got it working. I'll submit a PR soon. There's a couple issues I gotta work out.

<img width="339" alt="screen shot 2016-11-30 at 10 38 00 am" src="https://cloud.githubusercontent.com/assets/1680080/20758865/2f98ae7e-b6e9-11e6-9f2d-439204b63193.png">

**Comment by KeitIG** [comment]
Damn, sweet. I'll need to check how it looks on windows and ubuntu.
