### ISSUE TITLE
Avoid sync fs.realpathSync calls in reducers

### ISSUE THREAD

**Issue by YurySolovyov** [KeitIG/museeks#204]
While looking into #167, I noticed
```js
folders.forEach((folder) => {
    musicFolders.push(fs.realpathSync(folder));
});
```
I think it would be better to avoid doing it that way.

**Comment by KeitIG** [comment]
It will never exceed more than 100 elements (usually, it's just one), it's kind of an overkill.

**Comment by YurySolovyov** [comment]
@KeitIG shouldn't folders we get from `app.config.get('musicFolders')` already be resolved?

**Comment by KeitIG** [comment]
Good point.
