### ISSUE TITLE
Refreshing Library Takes forever

### ISSUE THREAD

**Issue by sarathkcm** [KeitIG/museeks#210]
Refreshing the library for new song additions is scanning the folder and building the library from scratch. Also, it takes a very long time to scan a collection of about 800 songs(no less than 5 minutes) while other players do it within 30-40 seconds.

**Comment by KeitIG** [comment]
Hello, it'll be fixed in 0.7.0 (will be out this week probably)

**Comment by sarathkcm** [comment]
Good to hear. Waiting. :+1:

**Comment by KeitIG** [comment]
It's out :) let me know if you still encounter any problems !

**Comment by sarathkcm** [comment]
I tried it. It is still slow, but definitely faster than before. It will be nice if refreshing the library is done as a background process and the user can start playing the songs added as soon as they are added to the library, while the library scan is in progress.

**Comment by sarathkcm** [comment]
Much of the UI gives a delayed response/ or is disabled while scanning the library. UI responsiveness can be improved.

**Comment by KeitIG** [comment]
@sarathkcm: I'm refreshing 3500 tracks in two minutes. What's your hardware ?

About responsiveness, that is something worth thinking about indeed.

**Comment by sarathkcm** [comment]
i7 5th Gen, 8 GB RAM, ordinary harddisk (Not SSD).

943 tracks, takes 9 minutes and 5 seconds to refresh the library in MUseeks.

As a comparison, the application called [MusicBee ](http://getmusicbee.com/)adds all the songs in 30 seconds. Also while MusicBee found 959 songs from the songs folder Museeks found only 943 songs. I couldn't say which songs were not added by Museeks because I will have to go through the list of songs to find out.

**Comment by YurySolovyov** [comment]
@sarathkcm it is probably ones in unsupported formats.

I wonder if you can try building [this branch](https://github.com/YurySolovyov/museeks/commits/ffmpeg).
It is older version, but uses different set of tools to do the playback and metadata extraction.

**Comment by sarathkcm** [comment]
I will try and post the results.

**Comment by sarathkcm** [comment]
@YurySolovyov ,I built ffmpeg branch from your fork and it performs really good in terms of refreshing the library. It refreshed in 50 seconds!.

There was another problem though. All the songs I tried to play, played only for 2-3 seconds and stopped.

**Comment by YurySolovyov** [comment]
@sarathkcm it is experimental branch, it worked for me last time I tested.

**Comment by sarathkcm** [comment]
@YurySolovyov  :+1:  for the library refreshing speed.
