### ISSUE TITLE
Better now-playing indicator

### ISSUE THREAD

**Issue by KeitIG** [KeitIG/museeks#212]
`<span class="mdi mdi-volume-up"></span>` is not extremly visible/appealing.

I love the one from Deezer. Steal it or create a similar one :smile: 

- [ ] Change the now-playing indicator with some animated one
- [ ] Clicking on it play or pause the player

**Comment by YurySolovyov** [comment]
I don't want to sign up and can't find relevant images on google, can you post the screenshot to give an idea?

**Comment by KeitIG** [comment]
![ezgif-2260823573](https://cloud.githubusercontent.com/assets/1311607/18581000/e12c56ac-7bfe-11e6-8706-854fd4406dd7.gif)
