### ISSUE TITLE
Checking or unchecking sleep mode option freeze the app

### ISSUE THREAD

**Issue by vprigent** [KeitIG/museeks#213]
In the later build, 7.0, the app completely freeze when i'm clicking on the checkbox which prevent the computer from going to sleep.

I'm then unable listen to music, interact with the app or even close the app
I'm on OS X 10.11.6, i'll try that at home on Ubuntu ASAP

EDIT > And I see nothing in the log

**Comment by vprigent** [comment]
As I expected, it's doing the exact same thing on Ubuntu ( 16.04 )

But there is more, it's a huge memory leak. I did'nt checked on OS X but on Ubuntu, it's causing a complete freeze of my computer in under 15 seconds.

**Comment by KeitIG** [comment]
Strange, I'll try to reproduce it when I get back home, thanks for the report !

**Comment by cfollet** [comment]
My museeks freezes too when i press on the checkbox.

**Comment by KeitIG** [comment]
I'm able to reproduce it, sorry for the inconvenience, I will investigate what is causing this.

**Comment by KeitIG** [comment]
Fixed by 8c5390269c6201a234150b04c97d2e6459559a9b

I'll release 0.7.1 to fix this. I'll tell you when it'll be online, then I'll close the issue.

**Comment by vprigent** [comment]
Great ! Thanks a lot, it's no big deal but I love to test your software, it's very promising

**Comment by KeitIG** [comment]
Well, I'll fix #215 first. Maybe not tonight. Tomorrow I hope. I hate this shuffle, bugs everytime.

**Comment by KeitIG** [comment]
AND DON'T LAUGH. THAT'S MEAN.

**Comment by vprigent** [comment]
Seriously ? I was waiting sooo long for a good cross platform music player ! I think i've found one with Museeks

Hope, i'll soon be able to fix the bugs I come across

**Comment by KeitIG** [comment]
There's still a long road until it becomes a decent player, but I hope for contributions/bug reports like yours to help me :)

**Comment by KeitIG** [comment]
Fixed in 0.7.1
