### ISSUE TITLE
Stop random play mess the song infos 

### ISSUE THREAD

**Issue by vprigent** [KeitIG/museeks#215]
When you use the random option, play some titles and stop random it mess the current song informations, giving the informations of the song playing before using random.

It happens on the "current song"  zone and on the list  "playing song" indicator

Steps to reproduce :

- Launch a song
- Ask for random songs, wait or go to next
- Stop random

Et voilà, you have mess with the current song information

🎵

**Comment by KeitIG** [comment]
Must be a problem with the shuffle rollback queueCursor.

**Comment by KeitIG** [comment]
Something more stupid, a not planned behavior. Imagine you shuffle your queue. You move from "Take five" to "Karma Police". The we disable Shuffle.

Do you agree we should still be on Karma Police and the next album song: "Exit Music" ?

**Comment by vprigent** [comment]
Yup ! I think it should be the default behavior, like 'I like that album, i'll stop shuffle in order to listen to watever song follows the current one on that specific album'

Actually, that part is ok, except that when I disable shuffle, it goes back to the last song before I shuffled

**Comment by KeitIG** [comment]
I'm sending you a build for Linux x64 (or tell me your prefered platform) , can you test it and tell me if the two bugs you reported are corrected ?

**Comment by KeitIG** [comment]
Here it is: https://drive.google.com/open?id=0Bya5ObHuu9mNWlh5Z3hFSXRLbnc

**Comment by KeitIG** [comment]
Fixed in 0.7.1

**Comment by vprigent** [comment]
Sorry to be late, well done, everything's all right on 0.7.1
