### ISSUE TITLE
Tabbed interface

### ISSUE THREAD

**Issue by jrohrauer** [KeitIG/museeks#216]
Greetings,

one feature I love from Foobar2000 is that I can have tabs. I have several tab with different genres/content (streams, Jazz, Pop, ... you get it). Here you can see what I mean:
http://ms-dos.org/demo/postings/foobar_tabs.png

This is something that would make Museeks way more sophisticated imho.

Cheers
Johannes

**Comment by KeitIG** [comment]
Hello,

this is an interesting feature, but it's not Museeks primary goal to offer a full-feature solution for now. We just want to offer a minimalistic and simple music player. I like the idea, but it won't be in Museek's 1.0 development roadmap. Maybe for a 2.0 ?
