### ISSUE TITLE
System Tray Icon

### ISSUE THREAD

**Issue by mazenamr** [KeitIG/museeks#219]
Can you add an icon in the system tray and allow museeks to run in the background.

**Comment by KeitIG** [comment]
I like the idea, but it's not doable for the moment. As the codebase changes at every release, I'll leave this open. Don't hesitate to +1 if you like it.

**Comment by YurySolovyov** [comment]
@KeitIG seems [totally doable](http://electron.atom.io/docs/api/tray/)

**Comment by KeitIG** [comment]
Yes I knew about that. I just didn't know how BrowserWindow would behave if `.hide()` was called with the app icon on the dock.

Ok, it's relatively easy to do. Now the question is: do we want it as an option or do we want the only way to close the app is a right click on the tray. Need tests on mulltiple platforms too + precise specs. 

I'll play with trays when I have time.

**Comment by YurySolovyov** [comment]
I think it is common to add an option like "Minimize to tray on close" or something like that.

**Comment by vprigent** [comment]
I've some concern about the interactions we've got with the window. 

And that's completely plateform independant. 
First, the close button is on the top left corner, that's right on Mac, not on default linux and windows. Secondly, we can't reduce nor full screen the window. That does not seems right to me. Is that a choice ?

I also like the System Tray idea, but I don't see that as a priority.

**Comment by KeitIG** [comment]
@vprigent A few things to say:

- I added an option to run Museeks with a native frame if people prefer to have them
- There's still not maximize/minimize buttons for various reasons you'll find at #41

Then, about the system Tray: 
- I have to check of they behave between Windows, Mac and Gnome
- If "minimize on close" is active, it's a bit poor for the UX: with one option, the app close, and with the other it minimizes. So I have to think about that to improve usability.
    - We can define an option in settings
    - We can ask for the user each time he clicks on the close button (like Mumble does for example)
    - If the second solution is chosen, I have to design/think about how to ask the user about that, we don't have any component that could "block the UI by asking something"

A whole lot of things that is not "that" simple :)

**Comment by YurySolovyov** [comment]
> We can ask for the user each time he clicks on the close button (like Mumble does for example)

I think that would cause a ton of annoyance to people. I'd be annoyed.

**Comment by KeitIG** [comment]
I'm currently working on this one.

- an option (default is true) let the user minimize Museeks  to tray
- when hidden, the tray appears, and Museeks can re-appear by clicking on the tray
- the tray has an option to kill Museeks

Tell me if I missed something
