### ISSUE TITLE
Create playlists

### ISSUE THREAD

**Issue by KeitIG** [KeitIG/museeks#22]
It implicates a new view, and contextmenus changes and a kinda heavy work to create reusable component.

- [x] Routing
- [x] Playlist view
- [x] Navigation
- [x] Create
- [x] Rename
- [x] Delete
- [x] Add tracks to playlist
- [x] Remove tracks from playlist
- [x] Dynamically update TracksList on playlist update
- [x] ~~Rearrange tracks in playlist (to be discussed)~~ later
- [x] Adapt `TracksList` to be usable elsewhere
- [x] Fix tracks load between Library and Playlist (tempfix)
- [x] Create playlist from TracksList
- [x] Adapt dark theme
- [x] Fix search in playlists

**Comment by KeitIG** [comment]
If anyone feel free to do that.

**Comment by KeitIG** [comment]
This must be done for 0.6, it's a too important feature, with a few big internal changes

**Comment by KeitIG** [comment]
existential question: should components should be loaded on `componentDidMount` or on route `onEnter` ?

**Comment by YurySolovyov** [comment]
I'd say on route enter, just to keep it a bit above components.

**Comment by KeitIG** [comment]
Got a problem here, playlists won't support "multiple times the same track by playlist". 
It's a big design issue I discovered randomly.

**Comment by KeitIG** [comment]
Hell yeah.
