### ISSUE TITLE
Sexify checkboxes in settings view

### ISSUE THREAD

**Issue by KeitIG** [KeitIG/museeks#221]
They are a bit sad.
- we can use ::after/::before with custom icons
- or react-toggle http://aaronshaf.github.io/react-toggle/ + custom styling

**Comment by YurySolovyov** [comment]
I'd prefer plain, but styled checkboxes as in Atom

![image](https://cloud.githubusercontent.com/assets/2168518/18711303/f2aa828e-8011-11e6-9630-7c3cbec97cdb.png)

**Comment by cfollet** [comment]
Any thoughts @Suriteka ?
