### ISSUE TITLE
Refactor action creators exports.

### ISSUE THREAD

**Issue by YurySolovyov** [KeitIG/museeks#222]
I think we discussed this on Gitter, but it is better to create a separate issue for this.
Basically, idea is that we should not embed methods directly into objects we're exporting, and and only export references to the actual functions.
So that instead of 
```js
export default {
    foo: () => { ... }
};        
```
we do
```js
const foo = () => { ... };
export default {
    foo
};        
```
This will simplify code reuse and refactoring.

**Comment by KeitIG** [comment]
I'm not sure that this changes antyhing with Webpack build process

**Comment by YurySolovyov** [comment]
- It is easier to visually enumerate what gets exported.
- It is easier to create "private" functions to enable code reuse.

**Comment by KeitIG** [comment]
Private functions/actions should not be in the same object as the actions anyway.

After some thoughts, I agree anyway, let's do this.

**Comment by cfollet** [comment]
Almost done.
