### ISSUE TITLE
Play button behavior when playerStatus is "stop"

### ISSUE THREAD

**Issue by cfollet** [KeitIG/museeks#223]
We do not allow the possibility to play a selected track using the play button. It's not user friendly IMO. 

To reproduce it select a track and just click the play button. 
- Expected behavior : Play the sound 
- Actual behavior : nothing happen. (and the play button change to pause even with no song playing, maybe another issue?)

**Comment by YurySolovyov** [comment]
With one condition: when there are no items in queue. Otherwise it might jump to selected track from paused one.

**Comment by cfollet** [comment]
Yes, sounds right

**Comment by KeitIG** [comment]
I disagree on this one. The behavior should be:

- If nothing is playing and I click the play button, then the current tracks list start to play

Tracks selection is not meant for that. What if you select multiple tracks ? Only play selected ones ? It introduces different behaviors, and it's not a good UX.

**Comment by YurySolovyov** [comment]
Well, AFAIK atm nothing happens at all

**Comment by KeitIG** [comment]
no shit :stuck_out_tongue_closed_eyes: 

Let's define what is the most obvious, we have multiple options:

- Disable the player controls when no track is playing (would hackfix #226)
- Start playing the current list
- Start playing the selected track(s?) (but I don't like this one)

**Comment by YurySolovyov** [comment]
I'm +1 on 2 or 3

**Comment by cfollet** [comment]
I am for **2**, you are right. Using 2 will aslo make the research more useful. For example, we will be able to play the search result by just clicking play, would be awsome. (It's iTunes behavior)

**Comment by KeitIG** [comment]
> But, using 2, what if the queue isn't empty?

I was thinking about that too. I'm not on Windows/Mac currently, can someone test how it's done on iTunes ?

**Comment by cfollet** [comment]
I think iTunes warns you, I will test that this morning.
