### ISSUE TITLE
Queue management when no song is playing

### ISSUE THREAD

**Issue by cfollet** [KeitIG/museeks#224]
Add to queue does nothing if we have not the player showing.

Also, I think we should never hide the queue icon, like iTunes. This will prevent some algorithm logic to show/hide the icon.

**Comment by KeitIG** [comment]
That was the case before. I introduced it when I refactored the `Header` and grouped `Queue`, `Progress` and `Cover`. I'll see what I can do about it without breaking the flex layout.

**Comment by cfollet** [comment]
Also, hiding the player leave an ugly blank area, we shouldn't hide anything IMO.

**Comment by KeitIG** [comment]
?

**Comment by YurySolovyov** [comment]
@cfollet screenshot?
