### ISSUE TITLE
Window location incorrect for multiple monitors

### ISSUE THREAD

**Issue by celynwalters** [KeitIG/museeks#228]
When Museeks was last used on a second monitor, it reopens in the same position.
For me, this is {-1312, 90}.
If I now only have one monitor connected Museeks is off the screen to the left.
The only way to get it back is to reconnect the monitor or edit the config file.
If both monitors were active I could use Win+Shift+Right to move it to my current one but this doesn't work when only one is active.
When switching from two screens to one when Museeks is already open, it successfully moves to the active one.

Only noticed on Windows 10, Museeks 0.7.1, can possibly try linux if desperate.

**Comment by KeitIG** [comment]
I thought I added a check about this. Seems like I didn't because I experienced it too. Thanks for the report :)

**Comment by code-hunger** [comment]
Can't you just maximize the window from the window list on the bottom of the screen?

**Comment by KeitIG** [comment]
@code-hunger: I don't know if we're talking about the same thing.

Here we just have to deal with screens max bounds.
