### ISSUE TITLE
Async or async-like search

### ISSUE THREAD

**Issue by KeitIG** [KeitIG/museeks#23]
Currently, the track search feature is called with an onchange event on the search input. With 100 tracks it's ok, but when you have 3000 of them, the search being synchronous take a huge amount of time and resources.

Search should be async. Something like:

- start to write in search input
- if nothing was written for like 400ms, then trigger search
(best solution imo)

or

- start searching onchange, but do not display anything
- if nothing was written for 400ms, then display results

just ideas.

**Comment by mrzmyr** [comment]
Do you mean the indexing or the track search itself ?

**Comment by KeitIG** [comment]
Sorry, was unclear. The track search itself.
