### ISSUE TITLE
Stop playing music when recovering from Sleep

### ISSUE THREAD

**Issue by simonv3** [KeitIG/museeks#232]
So I've been really enjoying Museeks and am pretty sure I'll be replacing iTunes permanently with it. Here's one thing that caught me off guard though:

Expectation: If I have music playing, when I close my laptop and open it later in the day (or early in the morning, as happened just now) I expect the music to not be playing.

What happens: when I open my computer again the music continues playing, which can be surprising.

For context: iTunes and Spotify stop playing music on closing the laptop. 

System: Macbook Pro w/ OS X El Capitan.

**Comment by KeitIG** [comment]
Fair concern indeed.

**Comment by KeitIG** [comment]
Ref http://electron.atom.io/docs/api/power-monitor/

**Comment by KeitIG** [comment]
It's done, I'm just waiting on a answer from the Electron team because it does not work on Linux.

**Comment by simonv3** [comment]
Awesome, thanks for the fast turnaround!

**Comment by KeitIG** [comment]
@simonv3 I'm afraid this won't work for Mac & Linux due to an upstream Chromium issue.

See https://github.com/electron/electron/issues/1615
