### ISSUE TITLE
Renaming a playlist causes weird reordering.

### ISSUE THREAD

**Issue by simonv3** [KeitIG/museeks#233]
When renaming a playlist it causes the playlist to jump around in the list of playlists, and causes weird selection issues.

![ezgif-3812670256](https://cloud.githubusercontent.com/assets/485583/19613905/52233124-979c-11e6-9e45-3c837b7a574f.gif)

Suggested fix:

Don't automatically sort playlists in alphabetical order, let users arrange playlists into their chosen order.

**Comment by KeitIG** [comment]
The current playlist implementation is extremly basic, and will be improved for sure. Something I don't get with your screencast (it goes too fast) is: is the list reordering while you're typing ? (it should not)

Note to myself:

- Don't allow empty string playlist name

**Comment by simonv3** [comment]
Yeah it reorders as I type, which is causing it to reselect and actually delete the text I had already written. 

I just noticed that the .gif cuts off halfway through what I recorded, let me try re-processing it. 

![ezgif-3812670256](https://cloud.githubusercontent.com/assets/485583/19613905/52233124-979c-11e6-9e45-3c837b7a574f.gif)

**Comment by KeitIG** [comment]
Okey, I can reproduce it, thanks for the report

**Comment by cfollet** [comment]
You can also see on the gif that the progress bar freezes when right click. (#225)
