### ISSUE TITLE
beforeunload handler causes app to close on refresh from DevTools

### ISSUE THREAD

**Issue by YurySolovyov** [KeitIG/museeks#238]
I tracked it down to this: [bc7b401](https://github.com/KeitIG/museeks/commit/bc7b401fd588c6bd58254fc022230b6ba9d2d749#diff-903dcab71c64a976160e32af8a47868fR77)

``` js
window.addEventListener('beforeunload', (e) => {
    // See http://electron.atom.io/docs/api/browser-window/#event-close
    e.returnValue = false;
    this.app.close();
});
```

We should find a better way to do this.

**Comment by dkniffin** [comment]
@KeitIG I can submit a PR to fix this. What was the original intention behind that code?

**Comment by KeitIG** [comment]
What has to be done is a bit more than just what's written here. Here's what I'd like (open to discussion of course)

- Tray is always visible, from startup to app quit
- So we don't need to handle `beforeunload` anymore
- When the tray option is enabled in settings, the only way to quit the app is Tray context-menu -> quit

So it should be fairly easy. If you have any questions, don't hesitate

**Comment by KeitIG** [comment]
Just to let you know what's happening now:

- tray is only shown when you click on the close button

**Comment by dkniffin** [comment]
Just wanna make sure I understand: for 3, it'd be a setting like "minimize on close"? And that would make it so the x button just minimizes to the tray.

**Comment by KeitIG** [comment]
yep, it would call `BrowserWindow.hide()` and not `minimize()` though.

If the option is not checked in the admin, it will close the app.

**Comment by YurySolovyov** [comment]
I this is broken again/still. Dev flow like fix->refresh->check does not work for me. It either errors or minimizes the app.
