### ISSUE TITLE
Tray Icon strange behavior ( edit )

### ISSUE THREAD

**Issue by vprigent** [KeitIG/museeks#240]
On MacOS, Tray Icon is displayed in full size :
Working on master dev mode, using Electron v1.4.3 with OS X El Capitan on iMac 27", the tray icon is used on tray without any resize of the image.

![Tray capture](https://cloud.githubusercontent.com/assets/5131277/19764689/9feadf2c-9c44-11e6-984e-6a13d924b323.png)

**Comment by YurySolovyov** [comment]
Possibly same issue on KDE 5:
![image](https://cloud.githubusercontent.com/assets/2168518/19764731/504d6382-9c4d-11e6-95d9-27e08dfbe9d6.png)

**Comment by vprigent** [comment]
Yup ! Will try @home on Ubuntu with Unity.

Easiest fix could be to resize tray icon ?

**Comment by YurySolovyov** [comment]
Works ok on Unity for me:
![image](https://cloud.githubusercontent.com/assets/2168518/19764956/7bc32f64-9c4e-11e6-9b49-07545af74194.png)

**Comment by vprigent** [comment]
There is more with the tray ... When you leave the app on OSX with `cmd + q` it add a tray icon that allows to reopen the app. This is some kind of unwanted feature but there is more, each time I try to quit the app, it adds a tray icon, meaning multiple tray icons are created.

**Comment by KeitIG** [comment]
- [ ] Check what size should be used for trays

About your last comment, I experienced it too, this is related to #238

**Comment by KeitIG** [comment]
@cfollet @YurySolovyov Can you change try different icons for tray here: https://github.com/KeitIG/museeks/blob/master/src/main-process/main.js#L89 and tell what's the best for you ? (probably 32, but I just need to be sure)

If it's 32, I'll add @2x version of the tray-icon too

**Comment by vprigent** [comment]
I tried a simple resize on  https://github.com/KeitIG/museeks/blob/master/src/main-process/tray.js#L10
`this.trayIcon = icon.resize({width: 24, height: 24});` gives me a correct icon.

**Comment by KeitIG** [comment]
the resize is a great idea indeed. Do you know how it behave with retina displays though ?

**Comment by vprigent** [comment]
I have no idea and I won't be able to test this ... 
It might not behave well on Windows/Linux with 4k screens either

**Comment by KeitIG** [comment]
okey, I'll try to test in on Windows by changing the element zoom level.
