### ISSUE TITLE
Performance issues on Library Refresh

### ISSUE THREAD

**Issue by vprigent** [KeitIG/museeks#242]
On OS X El Capitan, with Electron v1.4.3, Museeks be2ad47
Refreshing Library takes approximately forever.
With a folder of 25go and about 3200 tracks, it's been more than an hour and the process seems to have completely halt.

I've got `events.js:160 Uncaught Error: EMFILE: too many open files, open 'some_path'` errors and on resource monitor, the amount of data read by the Electron Helper process is about 220GB, and the computer was dead slow when scanning the folder ...
I'll update this issue as soon as I've discovered something

**Comment by YurySolovyov** [comment]
I would say that it's kind of known issue, it is due to how we extract metadata.

I would recommend trying to profile the app on smaller subset of your collection to see where time is spent. That would be very useful.

Also, can you try building older [experimental branch](https://github.com/YurySolovyov/museeks/tree/ffmpeg) and trying it on your collection?

**Comment by vprigent** [comment]
Yup ! I'll work on that this week-end :)
I suspect some recent changes to be responsible of that because it worked on 0.7 and last time I checked, it also worked at home, on Ubuntu. Just took about 2 ou 3 minutes

**Comment by KeitIG** [comment]
This metadata issue should not happen anymore, it's been fixed releases ago. 

Here, it's probably a matter of concurrency. In `LibraryActions.js:123`, can you change the fsConcurrency to a lower value and tell me how it goes ?

**Comment by vprigent** [comment]
That's what causes the issue. Defining `const fsConcurrency = 32;` does not block the refresh.
More, the perfs are substentially better, I could scan the whole folder ( 3207 tracks for a 26GB folder ) in 1mn 33 seconds.

**Comment by KeitIG** [comment]
That's the expected time
