### ISSUE TITLE
Can't open multiple instances of Museeks

### ISSUE THREAD

**Issue by KeitIG** [KeitIG/museeks#246]
I think it's due to a database lock issue. Do you think it's fine if we can't open multiple instances of Museeks at a time ?

**Comment by YurySolovyov** [comment]
Not sure. Think about concurrent database access.

**Comment by cfollet** [comment]
I am fine with it. There is almost no point opening  Museeks more than once.

**Comment by vprigent** [comment]
What is the interest of opening multiple instances of Museeks ?
I like the way it behave now.

**Comment by KeitIG** [comment]
ref: http://electron.atom.io/docs/api/app/#appmakesingleinstancecallback
