### ISSUE TITLE
Improve tray support

### ISSUE THREAD

**Issue by KeitIG** [KeitIG/museeks#253]
- [x] Fix shitty icon on Windows
- [x] Don't use `beforeunload` to create the tray (#238) 
- [x] Add doubleclick action -> open the app (linux and darwin)
- [x] Add click action -> open the app (win32)
- [x] Add player actions in contextmemu: play, pause, next, prev
  - [x] Fix play/pause toggle
- [x] When shown, the window should be focused
- [x] check that the icon is correct for MacOS

- ... ?

**Comment by KeitIG** [comment]
Just referencing #254 as it's being done right now.

**Comment by dkniffin** [comment]
I'm gonna do the player actions in the context menu.

**Comment by KeitIG** [comment]
Thank you, ipc events already exist for these actions. Just check the main-process files

**Comment by KeitIG** [comment]
253

**Comment by KeitIG** [comment]
Finished in #258
