### ISSUE TITLE
Initial volume doesn't match volume bar

### ISSUE THREAD

**Issue by dkniffin** [KeitIG/museeks#256]
The volume seems to start out at a certain level, but the initial value for volume slider in the app doesn't match up with that value, so as soon as you move the slider, the music gets a lot louder.

**Comment by KeitIG** [comment]
Can you handle it @dkniffin ? It's not a complicated one, it's juste some maths:

- The range input is from 0 to 1
- When we update it, we set the volume value to `Math.pow(value, 4)` to be more natural and we store that value to the config file
- At startup, the defaultValue of the range input is wrongly calculated
- See https://github.com/KeitIG/museeks/blob/master/src/js/components/Header/VolumeControl.react.js

**Comment by dkniffin** [comment]
Yep, I'll take care of it.
