### ISSUE TITLE
Monochrome tray icon

### ISSUE THREAD

**Issue by KeitIG** [KeitIG/museeks#259]
I have an .ai, I could do it myself, but if a designer passes around and want to create a white-monochrome version of the logo, I can share him the vector file.

- white version
- black version

**Comment by KeitIG** [comment]
poke @Suriteka :kissing:

**Comment by Suriteka** [comment]
If you can give me the .ai, I can create the monchrome icon for tray. 👍

**Comment by dkniffin** [comment]
We should probably have a black and a white version.

**Comment by Suriteka** [comment]
@dkniffin Yes probably like Google Drive or Creative Cloud one. 

<img width="474" alt="8de7bde96ac73ead8c62c46ed6429c82" src="https://cloud.githubusercontent.com/assets/5160323/20488699/48e5dd80-b008-11e6-935f-1477130f4682.png">

**Comment by KeitIG** [comment]
@Suriteka Marry me <3 I'm sending you two files: 

- the .ai
- the current tray icon so you can see how much margin you need to add to the png icon

**Comment by dkniffin** [comment]
@Suriteka Where are we at with this? If you don't have time, I could probably crank this out real quick.

**Comment by KeitIG** [comment]
<img width="1440" alt="screen shot 2018-02-06 at 13 08 27" src="https://user-images.githubusercontent.com/1311607/35859059-ef144a4c-0b3e-11e8-973e-6983f3e9362d.png">

**Comment by lottanbettan** [comment]
Is this useful?
[trayicons-monochrome.zip](https://github.com/KeitIG/museeks/files/1835191/trayicons-monochrome.zip)

**Comment by KeitIG** [comment]
They look really nice, let me try to implement that. Thank you so much ❤️

**Comment by KeitIG** [comment]
I quickly had a look at the whole stuff, I will convert those SVGs to PNG as they are SVG is not supported by `NativeImage`. I could also be a good opportunity to do #104 at the same time. It is currently a mess.

**Comment by lottanbettan** [comment]
Great! Thank you!
I changed the size and line thickness a little to look more "balanced" in its context and visible in its tray size. And converted them to PNG, see the 2 attached images below (one is white on white here on github = invisible).
![trayicon-monochrome-lightmode-v2](https://user-images.githubusercontent.com/32929295/37766055-19a721ea-2dc6-11e8-95e1-3e34bb392ae4.png)
![trayicon-monochrome-darkmode-v2](https://user-images.githubusercontent.com/32929295/37766054-19849cec-2dc6-11e8-81d5-476b4372c470.png)
Hope you like it, otherwise tell me, no hard feelings :-)

**Comment by YurySolovyov** [comment]
@lottanbettan can you post an example of how it looks on
1. Status bar
2. Black on White
3. White on Black

(cause you know, GH pages are white and it looks like an empty space :))

**Comment by lottanbettan** [comment]
Like that:
![screenshot](https://user-images.githubusercontent.com/32929295/37793086-ef891cb8-2e0d-11e8-85c6-b996c1197f09.png)
(The inverted version you can easily imagine :)

**Comment by KeitIG** [comment]
I did not think about the "use dark menu bar and Dock" option in the system preferences. I will check if there is a way to detect it with Electron

**Comment by KeitIG** [comment]
Found it, we actually do not even need the light version

https://electronjs.org/docs/api/native-image#template-image

**Comment by lottanbettan** [comment]
I love how active the development is around here :)

**Comment by KeitIG** [comment]
It is sporadic tbh. Sometimes I don’t do anything for 4 months :smile:
