### ISSUE TITLE
Remember values between open/close

### ISSUE THREAD

**Issue by dkniffin** [KeitIG/museeks#263]
This seems to have been implemented before in #42, but it's either broken or removed now.

I'd like for museeks to remember:

- [x] volume
- [x] window size
- [x] shuffle
- [x] repeat
- [x] ~~currently playing song (maybe)~~

**Comment by KeitIG** [comment]
Currently playing song -> nope.

If the other things do not work, there were a regression somewhere after 0.7.1.

**Comment by KeitIG** [comment]
Volume works, window size too

**Comment by dkniffin** [comment]
Volume does not work for me. Maybe it's because I'm running it via the electron app, instead of standalone museeks?

**Comment by KeitIG** [comment]
nah, my bad, it does not work indeed.

**Comment by KeitIG** [comment]
U_U I think the shuffle and the loop were never implemented

**Comment by dkniffin** [comment]
Yea, I figured as much. 👍
