### ISSUE TITLE
Fix React PropTypes validations

### ISSUE THREAD

**Issue by YurySolovyov** [KeitIG/museeks#279]
I think we missed that one cause we were running in prod mode all the time, but #276 revealed some issues we have

**Comment by KeitIG** [comment]
Can you list them ?

**Comment by KeitIG** [comment]
Also, can you fix them in your PR ?

**Comment by YurySolovyov** [comment]
I'd rather dealt with it on case-by-case basis, and landed PR first

**Comment by YurySolovyov** [comment]
@KeitIG list: https://gist.github.com/YurySolovyov/5579f9b106437b5f6e1a4fa843d78d84

**Comment by KeitIG** [comment]
:+1:

**Comment by KeitIG** [comment]
@YurySolovyov Do you think you will have time to work on it or can I handle it ? (I'd like to do it this week-end)

**Comment by YurySolovyov** [comment]
Sure, go ahead
