### ISSUE TITLE
0.1 release

### ISSUE THREAD

**Issue by KeitIG** [KeitIG/museeks#28]
App icon is missing.
That's so stupid I didn't even think about that.

**Comment by mrzmyr** [comment]
ref: https://developer.apple.com/library/mac/documentation/UserExperience/Conceptual/OSXHIGuidelines/Designing.html

**Comment by KeitIG** [comment]
Got a designer working on it.

**Comment by mrzmyr** [comment]
:+1:

**Comment by KeitIG** [comment]
The app is mostly bug-free. I'm just waiting for the designer to get his job done, it should be done shortly :) Then 0.1 will be ready and released.

**Comment by KeitIG** [comment]
Neverming, let's get this out. Icon will come.
