### ISSUE TITLE
Set one-var and padded-blocks linting settings to "never"

### ISSUE THREAD

**Issue by dkniffin** [KeitIG/museeks#280]
We talked about this in gitter, but an issue will make sure it isn't lost.

http://eslint.org/docs/rules/one-var
http://eslint.org/docs/rules/padded-blocks

**Comment by KeitIG** [comment]
What values for each of them ?

**Comment by dkniffin** [comment]
`"never"` for both.

**Comment by KeitIG** [comment]
I feel weird with both 

```
class  A {

    constructor(){
    }

}
```

and 

```
class  A {
    constructor(){
    }
}
```

I usually write 

```
class  A {

    constructor(){

        bla();
    }
}
```

**Comment by dkniffin** [comment]
:/ It's personal preference, but I really don't like the padding, especially if it's only at the beginning of classes and blocks. It makes it look really unbalanced.

**Comment by KeitIG** [comment]
But let's go for the padded block.

About one-var, I'm neutral.

**Comment by dkniffin** [comment]
So, you're good with both?

**Comment by KeitIG** [comment]
I am

**Comment by dkniffin** [comment]
Cool. I'll take care of this.

**Comment by dkniffin** [comment]
Should they both be errors?

**Comment by YurySolovyov** [comment]
Yes

**Comment by KeitIG** [comment]
Done in 47c754a818794012e14c0b39dbb954dd131dde2d and 846a743a2916a494389376d71186b2c839ea4e09
