### ISSUE TITLE
Add a setting for disabling native notifications

### ISSUE THREAD

**Issue by dkniffin** [KeitIG/museeks#281]

**Comment by KeitIG** [comment]
I was more thinking about the specific track-change, what do you think ?

(e.g we may always dispatch a notification when the library finished to refresh for example)

**Comment by dkniffin** [comment]
I'm fine with having a separate setting for just the track-change notification, but I think users should have the option to not get any notifications either. I know some people find them quite annoying.

**Comment by KeitIG** [comment]
ok, let's go for all notifications for now
