### ISSUE TITLE
Notification display delay

### ISSUE THREAD

**Issue by dkniffin** [KeitIG/museeks#286]
Between the time I click play and the the time the notification is displayed, there's about a 3 second pause. I'd like to remove that. I'm pretty sure it's either caused by [this line](https://github.com/dkniffin/museeks/blob/master/src/js/actions/AppActions.js#L39) or [this line](https://github.com/dkniffin/museeks/blob/master/src/js/actions/AppActions.js#L42)

**Comment by dkniffin** [comment]
Update: a little test shows it's 39.

**Comment by dkniffin** [comment]
@KeitIG It looks like `utils.getMetadata` is more performant here. You good with me using that instead of `app.models.Track.findOne`?

**Comment by KeitIG** [comment]
Notifications are instant for me. Db call is somewhat "meh", but "ok".

![screenshot from 2016-12-02 14 58 45](https://cloud.githubusercontent.com/assets/1311607/20836497/e37f566a-b89f-11e6-9f33-7fb69fa73543.png)

**Comment by KeitIG** [comment]
(how large is your library btw ?)

**Comment by dkniffin** [comment]
5510 tracks.

**Comment by dkniffin** [comment]
And yea, I'm noticing some intermittent behavior here. If I do the DB call, sometimes it's near-instant, sometimes it's 3-4 seconds.

**Comment by KeitIG** [comment]
Ok, so sometimes the DB call last 3 seconds... mmmh... I might be an index problem. I'll merge your PR for now, be we'll need to keep an eye on that stuff because this is somewhat important, we often do db calls.

**Comment by dkniffin** [comment]
Yea, makes sense. I think I saw some talk about switching DBs. Maybe this would be another reason to do so. ¯\_(ツ)_/¯

**Comment by KeitIG** [comment]
We already did. We moved from NeDB to LinvoDB for scalability reason. 

With 5000 elements, there's no way a DB call on an indexed field last 3 seconds. There's is a problem somewhere. Maybe the field is not properly indexed.
