### ISSUE TITLE
[Feature Suggestion] Remove Tracks from Library/Filesystem

### ISSUE THREAD

**Issue by fluffymadness** [KeitIG/museeks#295]
Maybe its already implemented, since I use the latest stable and not the git version.
Would it be possible to add a remove from library option, maybe with a dialog box that pops up asking if the file(s) should be deleted too.
I'd love to have this, listening a bit through my library right now and atm I have to open the explorer for every track I don't want anymore so that i can remove it.
The look from this app is nice and sleek, keep up that awesome work 👍

**Comment by KeitIG** [comment]
Hello, it will be implemented in #135, I'm currently working on it ;)

**Comment by vprigent** [comment]
Perhaps we should reconsider the ability to delete a file directly from the app ?
#227 is mainly a way for me to delete files, but also allows to rename/modify and easily find a file.

It does not seems a top priority to me, but advanced update and destroy operations seems a must-have on music player

**Comment by KeitIG** [comment]
@vprigent:

Let's create a new issue for that and discussions it there please :)

Some updates for this issue : this has been done on a local branch I will push when I consider it ready.
