### ISSUE TITLE
Add support for the opus file format

### ISSUE THREAD

**Issue by insanetesterftw** [KeitIG/museeks#296]

**Comment by YurySolovyov** [comment]
Blocked by #114 I guess

**Comment by KeitIG** [comment]
Chromium supports it, is it a file with metadata ? http://caniuse.com/#feat=opus

**Comment by KeitIG** [comment]
Apparently, Opus is just an OGG with the `.opus` extension, so nothing hard here.

**Comment by YurySolovyov** [comment]
@insanetesterftw can you provide an example file?

**Comment by KeitIG** [comment]
http://www.opus-codec.org/examples/
