### ISSUE TITLE
Slim down bundle size.

### ISSUE THREAD

**Issue by YurySolovyov** [KeitIG/museeks#301]
I'll track some stuff we can do to make bundle size smaller. No milestone, just stuff we can always take a look at. 
1. use `webpack.optimize.DedupePlugin()`. Super easy, just need to update `webpack.config.js`

**Comment by KeitIG** [comment]
Is it done ?

**Comment by YurySolovyov** [comment]
Nope, I have some more ideas. Will update post later.

**Comment by YurySolovyov** [comment]
Will close this for now, I'll try to keep an eye on bundle size.
