### ISSUE TITLE
Switch to Bootstrap 4

### ISSUE THREAD

**Issue by KeitIG** [KeitIG/museeks#314]
We are currently using Bootstrap 3 for most of our layouts. I would like to switch to Bootstrap 4 as soon as a stable version will be released.

- Includes files directly from npm package and build Bootstrap with Sass
- Define and overrides Bootstrap default variables
- Drop `bootstrap-sharper`

**Comment by v1r0x** [comment]
I saw museeks a couple of days ago on omgubuntu. Really like it! Although your program does not look _bootstrapy_ as most of the bootstrap applications, maybe [this](http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html) would be a cool addition to bs4 and a more _modern_ look?

**Comment by KeitIG** [comment]
Hello @v1r0x, we use Bootstrap mostly for some layout utils + some JS components. We indeed modified it a abit, because it's fairly easy to spot Bootstrap today.

About Materialize-like design, I'll be honest with you and I hate it haha. Mostly because of old projects I had to work with + Materialize doesn't make a lot of sense if you don't use Material Design guidelines from Google. Which is something Museeks is not doing (and will probably never do).

**Comment by YurySolovyov** [comment]
I was going to write something similar, but though that would be too harsh, but I kinda agree - Material Design is good set of rules to follow, but we don't have to literally copy it, and I think even Google encourages products to diverge and search for their own style, which is that we'll probably do.

**Comment by KeitIG** [comment]
I'll close this, imo we should use a simpler library or a fully custom one. (or maybe just a few key components from Bootstrap, like Reboot, the grid and utilities)
