### ISSUE TITLE
Default state of Settings -> Interface -> Minimize to tray

### ISSUE THREAD

**Issue by OutsourcedGuru** [KeitIG/museeks#317]
I think most programs in Windows/iOS/Linux start with the concept of small icons in some odd corner which allow the user to minimize/restore/exit.

This one has an x in the corner which by default behaves like a minimize button given the setting `Minimize to tray` which is initially set to **true**. This really faked me out, to be honest.

Without changing the x icon to something else, I would suggest that the easiest way to deal with this is to toggle the default.  In this way, it would behave in a more recognizable way for most users.

Perhaps a better long-term fix would be to programmatically change the x icon to something that looks like it will minimize (for example, an underscore character) if the toggle is ON.

**Comment by KeitIG** [comment]
You might be interested by https://github.com/KeitIG/museeks/pull/307 ;)

When you minimize to tray, you don't "minimize" the app, you hide it (it's not in your dock or taskbar anymore), so the cross makes sense imo.

**Comment by OutsourcedGuru** [comment]
@KeitIG Regarding 307:  yes, totally.

But if you did, I think I'd consider changing the X to something like:  https://www.google.com/search?q=hide+icon&biw=1217&bih=716&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjgy5yrsrPSAhUnslQKHdLtDrAQ_AUICCgB
