### ISSUE TITLE
PlayIndicator status suggestion

### ISSUE THREAD

**Issue by OutsourcedGuru** [KeitIG/museeks#318]
I've seen the existing play-indicator before and I suppose it does the job of indicating that the song is playing (say, if your external volume is too low for you to hear).  I've looked at the animation portion in your CSS and it's just randomly changing the themed heights of three bars when the state is in the play mode.

I was just looking at [these sprites](http://wiki.jqueryui.com/w/page/26308090/ThemeRoller%20icon%20set), specifically the ones near the bottom which you'd normally use to indicate how many bars your cellphone has.  There appear to be five which range from "all four bars" down to "zero bars".  It strikes me that these could be used individually to display as a dynamic volume indicator...

So in theory, something would bind to your same ProgressBar updates instead of the approach you're using in _view-common.scss.  And it would be responsible for measuring the, say, left channel output in realtime volume and then do a weighted division-by-five of that number, resulting in zero through four as the output.  The output then would indicate which of the five sprites to select from the cached group of five.  When the volume is soft, it would display the second-to-the-last icon here, for example.

Hopefully that makes sense.

![themeroller-icon-set-vector-32px-a-2010-06-01](https://cloud.githubusercontent.com/assets/15971213/23383766/e6cdc008-fcfc-11e6-9d48-d0fb2d5c7595.png)

**Comment by KeitIG** [comment]
> Hopefully that makes sense.

I'm afraid I don't get it precisely :stuck_out_tongue: 

You are making the assumption that the the PlayingIndicator is to show the volume of the music, when it is only used to show what music is currently playing. So you would update the animation with different levels depending of the volume value ?

**Comment by YurySolovyov** [comment]
I don't think we have an infra in place to detect sound amplitude of channels

**Comment by KeitIG** [comment]
Oh, so a minigraph of the the track being played right now ?

**Comment by OutsourcedGuru** [comment]
Well... a *great* indicator would be something like a mini equalizer feedback which detects the bass/midrange/tweeter dynamic volume and would display this dynamically.  (If there was thudding bass during the song the left-most column would pop up in time with that sound, in other words.)

But I've looked into the difficulty of doing this.  It's actually quite do-able but requires a short list of new browsers.  For example: http://vikaslalwani.com/music-player/ (But just imagine three columns across and a tiny version of this.)

There's another good example here:  https://dzone.com/articles/exploring-html5-web-audio (see "Create a Volume Meter")  https://youtu.be/JrfsZUG0Ijc

Backing up from that *great* version, I was thinking that you could swap out five levels of simple dynamic volume while the song is playing.  And you'd use that collection of images out of that sprite I provided which is in the jquery publishing space.

@YurySolovyov I guess that was what I was asking about... "is there a place within the interface to tap into the audio object and ask it for its current dynamic volume at any moment in time?"

**Comment by YurySolovyov** [comment]
> "is there a place within the interface to tap into the audio object and ask it for its current dynamic volume at any moment in time?"

None that I know of

**Comment by OutsourcedGuru** [comment]
Fair enough.  Should I close this?  (Kind of a noob at all this.)

**Comment by YurySolovyov** [comment]
yup, it is ok to reopen it once it is relevant
