### ISSUE TITLE
Making money through iTunes Affiliate Program, for example

### ISSUE THREAD

**Issue by OutsourcedGuru** [KeitIG/museeks#319]
Just throwing this out there...

Looks like Apple's iTunes has an [Affiliate Program](http://www.apple.com/itunes/affiliates/) which you, in theory, could incorporate into your player.  In theory, if you provide a link to iTunes and the user follows that link then you get a small percentage of anything they buy from that session.

So the usual way something like this might work would be... I might be listening to a song from the Beatle's White Album and your app then would display the cover art from that.  If I, the user, then click on that it might take me to the iTunes store for that album and if the user buys anything during that sesssion it's tagged with your affiliate token or something and you'd make something in the way of a commission.

Granted, Apple is kind of a pain in this space with the hoops they make you jump through.  But if your code becomes super-popular someday it might turn into some money.

[link maker](https://autolinkmaker.itunes.apple.com/)

**Comment by KeitIG** [comment]
Hey :)

Thanks for the idea, that's interesting, but won't be implemented as Museeks is not a commercial project. The few things I need to pay (basically domain name, host and logo) are on my funds.

That is really interesting though, I will keep that in mind in the future.

**Comment by OutsourcedGuru** [comment]
Not a problem.  I'm loving this little player and have tweaked mine already from "day 1".  (Thanks.)

**Comment by KeitIG** [comment]
![oh__stop_it__you__by_rober_raik-d4cwd9f](https://cloud.githubusercontent.com/assets/1311607/23452220/d43d6778-fe63-11e6-9b06-2735c53340f8.png)

**Comment by OutsourcedGuru** [comment]
Gave you some love [over here](https://outsourcedguru.wordpress.com/2017/02/28/how-cool-is-electron/), too.
