### ISSUE TITLE
Noting a Windows RADAR HeapLeakDetection for Electron.exe

### ISSUE THREAD

**Issue by OutsourcedGuru** [KeitIG/museeks#320]
Could be Electron.exe itself of course, but my own registry (Windows 7 Professional 64-bit) has flagged electron.exe with an...

`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\RADAR\HeapLeakDetection\DiagnosedApplications\electron.exe`

...entry.  [RADAR](https://channel9.msdn.com/Shows/Going+Deep/RADAR-Windows-Automatic-Memory-Leak-Detection)

Not sure if RADAR is on by default or not.  Might be worth downloading the [Microsoft Application Verifier](https://www.microsoft.com/en-us/download/details.aspx?id=20028) if you wanted more detail.

Please note that I've also tested the Electron-based Pencil app on my computer.  Unfortunately I can't determine exactly *when* that registry entry was flagged.  <_<

**Comment by KeitIG** [comment]
Does it happen during library refreshing ?

**Comment by OutsourcedGuru** [comment]
I'm not completely convinced that it's Museeks that's throwing it, to be honest.  I'll test this evening (and abuse it a little with spastic behavior) and see if Application Verifier sees anything.  Like I said, it could have been Pencil what-done-it.

**Comment by OutsourcedGuru** [comment]
Guys, I think you're good.  I've not been able to find anything after a fair bit of testing.  It must have been Pencil instead.
