### ISSUE TITLE
Combine reducers using provided method by redux

### ISSUE THREAD

**Issue by SirWindfield** [KeitIG/museeks#329]
I wanted to ask on why you aren't using the defined method `combineReducers` from redux to combine all your reducers to a single one within [index.js](https://github.com/KeitIG/museeks/blob/master/src/js/reducers/index.js)?

**Comment by YurySolovyov** [comment]
See https://github.com/KeitIG/museeks/pull/205

**Comment by SirWindfield** [comment]
Well, aside from small refactoring, there shouldn't be any problem. Just curious on why you didn't use `combineReducers` from the beginning. Your current solution feels more of a hack tbh. Don't take this offensively :)

**Comment by YurySolovyov** [comment]
> Just curious on why you didn't use combineReducers from the beginning. 

I think @KeitIG started with Flux, and then we moved to Redux

> Your current solution feels more of a hack tbh. Don't take this offensively :)

It is, though it works. No offence taken :)

**Comment by SirWindfield** [comment]
Thanks for the answers :smile: If I find some time I can make a PR and use `combineReducers` if you want to move to the function.

**Comment by YurySolovyov** [comment]
I'm ok with it, @KeitIG thoughts?

**Comment by KeitIG** [comment]
Museeks was initially using Vanilla Flux, then we switched to Redux, but there are still some vanilla-flux patterns you will see across the code. 

Any improvements are welcome as long as their cooresponding PR describes what has been changed and what it improves

**Comment by YurySolovyov** [comment]
I think this can be closed now
