### ISSUE TITLE
Reveal file in finder / directory

### ISSUE THREAD

**Issue by simonv3** [KeitIG/museeks#330]
It'd be great if when I right click on a file one of the menu options would be "View file in <whatever system file browser is>". 

In Mac OS X this would be the finder, Explorer in windows?

**Comment by KeitIG** [comment]
It's been done already and will be released un 0.8 :)

**Comment by KeitIG** [comment]
Ref https://github.com/KeitIG/museeks/pull/227

**Comment by simonv3** [comment]
Ah, sorry! I searched for some of the keywords but GitHub didn't turn up anything. Thanks for doing this :)

**Comment by KeitIG** [comment]
yes, it was PR directly proposed without any issue opened :)

**Comment by KeitIG** [comment]
It's beed release @simonv3 ;)

**Comment by simonv3** [comment]
@KeitIG Thanks!

When I download Museeks from the website and install it by dragging it - and replacing the existing install - into the Application folder (on OSX) I get: 

```
Check with the developer to make sure Museeks works with this version of OS X. You may need to reinstall the application. Be sure to install any available updates for the application and OS X.

Click Report to see more detailed information and send a report to Apple.
```

I'm running OS X 10.11.6 - El Capitan.

**Comment by KeitIG** [comment]
Can you poke me on Gitter, so we can try to solve this ? https://gitter.im/KeitIG/museeks
