### ISSUE TITLE
macOS integration issues

### ISSUE THREAD

**Issue by KeitIG** [KeitIG/museeks#337]
I had some time to test Museeks on Mac, and it's not perfect

- [x] Museeks interrupts logout (cf. screenshot)
- [x] Museeks does not show if minimized to tray + click it's in the dock
- [x] Right-click on the dock icon + quit doesn't quit the app
- [x] Native window controls
- [x] Fix-multiselection #368 
- [x] Native font

![screen shot 2017-04-04 at 10 33 20](https://cloud.githubusercontent.com/assets/1311607/24648120/dacc9fb2-1922-11e7-93c6-8b79b723319b.png)

**Comment by KeitIG** [comment]
All help from a active mac user would be greatly appreciated

**Comment by hipunk** [comment]
I noticed the same, also the window buttons are located at the wrong side of the window (which can be "fixed" by using "native frame", but still...).

But other than that I am quite happy so far. Other electron music players fail miserably in comparison.

What kind of help do you need? Logs etc. or active development work?

**Comment by KeitIG** [comment]
> Other electron music players fail miserably in comparison.

You do have no idea about what it means to me, thanks.

---

- About these problems, I need to do some researches on Atom and electron researches first.
- About the window controls at the left, this can be easily fixed actually, I'll submit a PR for this, can you confirm that the controls order in mac are close/minimize/maximize ?

**Comment by hipunk** [comment]
Glad to hear that!

- Same for me!
- Yes, it is close, minimize and maximize from left to right.

**Comment by KeitIG** [comment]
Would it annoy you if they had the same design or would you prefer the mac-like colored window controls?

**Comment by hipunk** [comment]
I would prefer the mac-like coloring by far!

**Comment by KeitIG** [comment]
So I guess your main problem with the native frame is this is the native frame is not dark right ?

**Comment by hipunk** [comment]
It is no big deal, but it would look a tad nicer, if you know what I mean.

**Comment by KeitIG** [comment]
kk, just analyzing your usecase so I know what to work on exactly ;)

**Comment by hipunk** [comment]
No problem mate, we also need to implement shortcuts for minimizing, closing the window, hiding the app and the preferences.

**Comment by hipunk** [comment]
I'm sorry, this is slightly offtopic but is there a way to communicate with you in a quicker way (irc, discord or similar)?
I am struggling to get the museeks package running with electron ("webpack --config webpack.config.js --progress --colors") seems to fail when running npm install && npm run compile.
I'm trying that, because I would like to contribute.

**Comment by KeitIG** [comment]
Yes sure, go and chat with us on Gitter: https://gitter.im/KeitIG/museeks

**Comment by KeitIG** [comment]
I got a mac at work, I will be able to work on these issues from now.

**Comment by KeitIG** [comment]
Work in progress

![screen shot 2017-12-05 at 18 20 35](https://user-images.githubusercontent.com/1311607/33620765-1946193a-d9e9-11e7-8591-8ddf01e42209.png)

**Comment by YurySolovyov** [comment]
@KeitIG are these window buttons native or custom?
If they are custom we should make sure they exactly reflect the position of native ones

**Comment by KeitIG** [comment]
They are native :)
