### ISSUE TITLE
Should we use system fonts?

### ISSUE THREAD

**Issue by KeitIG** [KeitIG/museeks#340]
https://css-tricks.com/snippets/css/system-font-stack/

**Comment by YurySolovyov** [comment]
Tradeoff: consistency of app on different platforms vs. consistency with other apps on a particular platform.
TL;DR: do we want to look same on all platforms or a bit different on each one?

**Comment by KeitIG** [comment]
That's exactly the question. Personally, I would love to use the system font for consistency. I would look a bit more native. But that's personal.

**Comment by YurySolovyov** [comment]
I'm also leaning towards being closer to native looks than to being internally consistent

**Comment by KeitIG** [comment]
System fonts are used on macOS as the app looks more integrated. There is a fallback on OpenSans for Linux/Win as the fonts sometimes looks weird.

Closing it for now, feel free to continue the discussion.
