### ISSUE TITLE
library columns enhancements

### ISSUE THREAD

**Issue by danidev** [KeitIG/museeks#341]
Hello, I just tried museeks and I found it very good and it could be a valid (if not the best) mp3 player for linux, if you keep it so minimal and clean.

I just want to point you to some important enhancements that in my opinion must be done on the library component:
1. first of all, the table lacks the availability to **sort columns**, for instance you cannot sort by artist or album, that is quite a pain, eventually multiple sorting, i mean: by artist and by album
2. in settings will be very useful to **choose which columns to display** in library, because, for instance I need the track number and year to sort by artist->album->year->track number
3. **resizing columns** could be very helpfull

I will be very glad if you will find this comment helpfull.
Thank you and keep the good work!
Daniele

PS. I would like to contribute but I've seen you use react, while I use angular for my day-time job, so I need to learn it first and I think it requires a pretty huge pattern shifting... ;-)

**Comment by KeitIG** [comment]
Hellp @danidev !

Everything you mentioned is here: https://github.com/KeitIG/museeks/issues/62, sorting columns will come first as it's the easiest thing to implement :)

>  I would like to contribute 

There are some tasks fairly easy to do if you're afraid with React
