### ISSUE TITLE
Any headway on Album/Artist View?

### ISSUE THREAD

**Issue by jacobsax** [KeitIG/museeks#343]
Was any headway ever made on building Artist or Album views? I noticed that some issues were raised last year but seemed to be closed without any pull requests being made. If not, I'll have a look at adding the functionality over the next couple of weeks.

- [ ] Add an Album view, order by Artist and then by Album, where selecting the Album shows all tracks in that Album.
- [ ] Add an Artist view, where selecting an Artist shows all tracks by that Artist - grouped by Album in orderings.

**Comment by igorer88** [comment]
Yeah. It would be great.

**Comment by KeitIG** [comment]
Hello @jacobsax and @igorer88 !

I started to anticipate the work on this with some refactoring in 0.8 release. The "official issue" for this is #130 though. We can discuss about the specs you'd like to see there if you want :)
