### ISSUE TITLE
Scrollbar too small

### ISSUE THREAD

**Issue by bspeice** [KeitIG/museeks#344]
The current scrollbar (I'm testing on Ubuntu) is too thin, such that it's impossible to drag without switching to the native frame. Whenever you go close, the pointer switches to resize instead of drag.

Using the native frame fixes this, but I wanted to raise the question since I imagine it's fairly simple: Can the scrollbar be made longer?

**Comment by KeitIG** [comment]
Yep, a problem I've been thinking about. I'll try to reprioritize it :) thanks for the feedback
