### ISSUE TITLE
Support dragging in seekbar

### ISSUE THREAD

**Issue by ketanhwr** [KeitIG/museeks#346]
Hi, in the seekbar of the current music playing, the only thing you can do is click on a particular instant of the bar and the music starts playing on that moment. Having used a few other players, I think that allowing dragging the seek point in the bar will be a really helpful feature.

**Comment by KeitIG** [comment]
Seems like we got a regression here, it's supposed to be supported. Thanks for the report!

**Comment by ketanhwr** [comment]
Thanks! :slightly_smiling_face:

**Comment by ketanhwr** [comment]
Btw, I'd love to contribute! This is one of the few music players for Linux with a really good design. I've worked in React as well as Electron before, can you tell where can I get started?

**Comment by YurySolovyov** [comment]
Take a look at [starter tasks](https://github.com/KeitIG/museeks/issues?q=is%3Aissue+is%3Aopen+label%3A%22starter+task%22)
