### ISSUE TITLE
Update notification if there's already one open.

### ISSUE THREAD

**Issue by complexSandwich** [KeitIG/museeks#358]
I'm running Elementary OS (Loki) and whenever I skipped a song, a new notification would open.  I would have a bunch of notifications open and it was annoying.  So I added a tag to the notification object, so now it will update the notification if there's one open.  If other people are interested in this I can make a pull request.

As a side note, when I ran npm run lint, I got this:

npm ERR! Linux 4.10.0-33-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "lint"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! museeks@0.8.1 lint: `eslint . --config .eslintrc --cache`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the museeks@0.8.1 lint script 'eslint . --config .eslintrc --cache'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the museeks package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint . --config .eslintrc --cache

**Comment by KeitIG** [comment]
Hello :)

Thanks for the feedback, I will see if we can have only one notification at a time

Ref:  https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API#Replacing_existing_notifications

**Comment by KeitIG** [comment]
About, the linting, is that the only errors it gives you

**Comment by complexSandwich** [comment]
Sure, I just added the tag option in NotificationActions.js.

As for the error, I looked at it again and it was because I didn't put a trailing comma after the tag option.  Oops.

**Comment by KeitIG** [comment]
@complexSandwich I didn't understand you fixed the problem yourself in a custom build, feel free to open a PR :)

**Comment by KeitIG** [comment]
For the record, I do have one weird bug on elementary OS, I think it is Gnome related, or Electron related.

When the Slack app sends a notification, it displays the Museeks icon.
