### ISSUE TITLE
Middle Mouse Click UI Improvements 

### ISSUE THREAD

**Issue by Nino9614** [KeitIG/museeks#360]
First of all great app using it a while know and it works fine so far :).
But i have one suggestion. Have you ever tried to click on a ui component with the middle mouse button?
On some components (i guess "<a>" tags or some kind of component with link interaction or redirect) it opens the new "screen/view" in another window instance (see screenshot)

![image](https://user-images.githubusercontent.com/27356972/30064678-cb7792b6-9252-11e7-9ede-dca59d298260.png)

Thats all from a single instance of the application. When you click on the playlist tab for example you get a screen/window like this.

![image](https://user-images.githubusercontent.com/27356972/30064746-0312af94-9253-11e7-9911-5423ccd05c30.png)

Its now something to important, but i think it should be fixed because it causes unexpected behavior for the user.
I only know this because of a electron application i work on, so the same thing happend to me xD

**Comment by KeitIG** [comment]
First thing. LOOOOOL.

I was totally unaware of this! This is definitely a bug, thank you for the report :)

for the record, it's the case on all links.

**Comment by KeitIG** [comment]
@YurySolovyov I only found this solution https://stackoverflow.com/questions/44578022/electron-prevent-middle-click, I don't know if you have a better idea. I would have expected something at the Electron level.

**Comment by KeitIG** [comment]
nevermind

```
mainWindow.webContents.on('new-window', (event) => {
    event.preventDefault();
});
```

seems to do the trick
