### ISSUE TITLE
Performances improvements

### ISSUE THREAD

**Issue by KeitIG** [KeitIG/museeks#363]
### TracksList

- [x] ~[use passive events](https://github.com/facebook/react/issues/6436#issuecomment-253082849)~
- [ ] `will-change` css property?

### Others

- [ ] Make CPU benchmarks

**Comment by YurySolovyov** [comment]
> Make CPU benchmarks

You mean to profile stuff?

**Comment by KeitIG** [comment]
yes, strange thing is passive events add CPU usage O___o I just wanted to do a quick check-up of the performances of the app, as Electron is quite a resource-heavy solution.
