### ISSUE TITLE
Performance on huge libraries

### ISSUE THREAD

**Issue by SirWindfield** [KeitIG/museeks#369]
I just wanted to ask how the performance is when libraries are used that contain 10000+ songs. I added my folders and museeks is still scanning for about 7 hours now...

I checked the console but there weren't any errors displayed.

I took a quick look into the state and noticed that you store every song there. Isnt that quite RAM eating? Not sure if it is enough information to increase the ram usage up by a lot.

**Comment by KeitIG** [comment]
Hello :)

I do have a library of 6000 mp3 (around 20GB), and it is being scanned in less than a minute, which is quite fair :smile:

It is strange that you get 7 hours of scan without any warning. Are you using a HDD or a SSD? What is the exact size (in weight) of your library?

**Comment by SirWindfield** [comment]
Thanks for the reply!

My library is about 200GB large. Mostly a mix of flac,wav and mp3 files. The number of songs is around 30000. 
I made sure to start museeks directly in dev mode and now I get an error. Though that the stack trace isn't that useful ([gist](https://gist.github.com/SirWindfield/c38521231371000107482aef531027dc)).

**Comment by YurySolovyov** [comment]
I think problem is somewhat in the way we get metadata - some code paths may cause reading a significant portion of the file before we get the metadata.

@SirWindfield do you have a large number of mixes like when entire album/mix is in one file?

**Comment by SirWindfield** [comment]
@YurySolovyov No I do not have. The largest files are usually podcasts. 
Can you help me out real quick? I downloaded the repo, installed electron globally and want to run it using `yarn run dev` but the electron instance doesn't load from the provided dev-server. Did I forget something?

**Comment by KeitIG** [comment]
The only things I see here is some files are not having metadata headers but this is fine and fallbacks are ready for this scenario.

It would be interesting that I build the latest version of Museeks from sources and make you test it to see if you can still reproduce it.

(I just need to finish what I am working on and I hope it will be finished in the next days)

**Comment by SirWindfield** [comment]
Thanks. I will gladly test it out. Best would be to push the branch upstream and let me build itself because I am currently running on a metered connection (isp is changing some cables down the road).

What about the error caused by your `musicmetadata` dependency? Looks like it tries to format some nonexistent tags for some odd reason.
If I remember correctly, `yarn` warned me that I should use `music-metadata` instead. Maybe the author pushed some updates onto that library instance concerning the bug. Might be worth an investigation.

**Comment by KeitIG** [comment]
@SirWindfield Could you clone the repo, build and run the app and tell me if the problem still exists? Do not forget to delete `~/.config/museeks` first, just in case.

**Comment by SirWindfield** [comment]
Just did that. Same as before. Loads all files. The last event triggered is an update event. After that, the window content doesn't change and I won't see any items added to my library. If I restart the app, the view actually contains them.

**Comment by KeitIG** [comment]
I think the problem was just loading the whole library after a scan. It can take quite some time depending of the size of the library.

Let's merge this issue with #414
