### ISSUE TITLE
Switch to music-metadata?

### ISSUE THREAD

**Issue by KeitIG** [KeitIG/museeks#371]
- https://www.npmjs.com/package/musicmetadata
- https://www.npmjs.com/package/music-metadata

As shown by @SirWindfield in #369 

`music-metadata` seems to support more format and would allow us to not use an external library for WAV.

**Comment by YurySolovyov** [comment]
Yeah, but even that module may cause reading the entire file. Worth a try tho.

**Comment by SirWindfield** [comment]
Isn't knowing the duration of a song the only case where you need to read the entire file? Out of my head the specifications for id3,wav and vorbis all are some header metadata and (for vorbis if I remember correctly) some seeking at the end of a file. Not sure how node handles I/O but seeking shouldn't load the entire file.

**Comment by YurySolovyov** [comment]
Yes, by reading I meant "reading through"

**Comment by KeitIG** [comment]
This is currently happening with `musicmetadata` anyway. It goes through the whole stream.

**Comment by YurySolovyov** [comment]
I know `ffprobe` gets metadata consistently fast, but that's native code/binary.
One possible way could be to compile and expose it via WASM, but that's challenging :)
