### ISSUE TITLE
tracksCursor enum

### ISSUE THREAD

**Issue by YurySolovyov** [KeitIG/museeks#372]
In https://github.com/KeitIG/museeks/pull/370#discussion_r155187162 I spotted this:
```js
tracksCursor: 'library', // 'library' or 'playlist'
```
and suggested creating an enum like:
```
tracksCursor: cursorTypes.library
// or
tracksCursor: cursorTypes.playlist
```

**Comment by KeitIG** [comment]
Working on the sorting features, I might have found a way to get rid of the enum and this all/sub system.

_Reminder: this system exist to avoid janks in the `TracksList` component._

The potential solution would be to start from: 

```
const initialState = {
  tracks: {
    library: {
      all: null,
      sub: null,
    },
    playlist: {
      all: null,
      sub: null,
    },
  },
  tracksCursor: 'library', // 'library' or 'playlist'
};
```

and arrive to something more decent:

```
const initialState = {
  tracks: {
    library: {
      all: null,
      sub: null,
    },
    playlist: {
      all: null,
      sub: null,
    },
  },
  search: '',
  sort: {
    by: 'ARTIST',
    order: 'ASC'
  }
};
```

The idea would be to make use of the `mapStateToProps` in `Library.react.js` and `Playlist.react.js`, and do the filtering/sorting there. By keeping the scroll and selection state in `TracksList` and moving these things to `mapStateToProps`, we might simplify a lot state management with a minimal performances loss.

**Comment by YurySolovyov** [comment]
Sure, that's even better, one less concept to worry about

**Comment by KeitIG** [comment]
This was actually how things were before (loooong time ago), but things would get slower in O(n), n being the total number of tracks in the library. I will try implementing it now and see if it goes well.
