### ISSUE TITLE
Error when opening second instance of app

### ISSUE THREAD

**Issue by rinklejain** [KeitIG/museeks#375]
When opening second instance of the app, an error dialog box pops 
(using node.js version 6.10.0)

![museek](https://user-images.githubusercontent.com/17960706/34640987-ff1a6c20-f322-11e7-8886-26b55687e198.png)

A way to solve it can be solved as mentioned [here](https://github.com/electron/electron/issues/8862#issuecomment-294303518)

**Comment by KeitIG** [comment]
Thanks for the report. Does it happen with a custom build or the latest release?

**Comment by rinklejain** [comment]
It happened with custom build from the current master branch.

**Comment by KeitIG** [comment]
I just tested on macOS, when I try to run a second instance, the second process in killed before it initiates the app. I will need to try on Ubuntu.

**Comment by KeitIG** [comment]
I can reproduce it on Ubuntu, I will investigate

**Comment by KeitIG** [comment]
An up-to-date version of the screen with the latest main-process refactoring:

<img width="545" alt="screen shot 2018-04-02 at 23 42 35" src="https://user-images.githubusercontent.com/1311607/38217685-8d0cd9ec-36cf-11e8-8403-61ba3eafcb4e.png">

And the line: 

```this.workArea = electron.screen.getPrimaryDisplay().workArea;```

**Comment by KeitIG** [comment]
Found the solution there: https://github.com/electron/electron/issues/8862

**Comment by KeitIG** [comment]
Fixed in 16079935b963b1e5a355f3a0126dc270e86c2cea
