### ISSUE TITLE
Replace PNG icons with SVG

### ISSUE THREAD

**Issue by a2nt** [KeitIG/museeks#386]
SVG icons fits better QHD+ displays

**Comment by KeitIG** [comment]
What icon are you thinking of?

**Comment by a2nt** [comment]
All of them SVG is just more advanced way to have application icons

**Comment by KeitIG** [comment]
If you are talking about the App icon itself, each OS expects a different format. PNG for Linux (maybe it accepts SVG though), ICNS for macOS and PNG for Win32.

Are you saying that the PNG 256 icon for Linux is not enough and there is a resolution problem on QHD+?

**Comment by a2nt** [comment]
Most gnome 3 applications use SVG right now - it's just easier to scale. Also I had a problem at issue #389  thought it's because of small original file size, but actually it was caused by resize function. I have fixed it at submitted pull request #388

**Comment by KeitIG** [comment]
Interesting, I will try to see how we can still support Gnome 2 though (I think Pantheon and Mate are still based on it).

**Comment by KeitIG** [comment]
From what I see [here](https://www.electron.build/icons), Electron builder does not support SVG and bases its icon on the ICNS file. Are you currently seeing a blurry icon or ...? Maybe I could update the ICNS.

**Comment by KeitIG** [comment]
The ICNS file contains a 512x512 version of the logo, I think it is more than enough
