### ISSUE TITLE
[BUG] New music that you add to playlist isn't added to playback queue

### ISSUE THREAD

**Issue by a2nt** [KeitIG/museeks#387]
To repeat it:
1) create new playlist
2) add one song into the playlist
3) play this song from the playlist
4) while the song is playing add an other one
Playback will be stopped after the first song

**Comment by KeitIG** [comment]
Ah, interesting one. I would like to say, "it's not a bug, it's a feature".

Adding a track to a playlist being played will not see this new track added to the queue indeed. The way we play the tracks is context agnostic for now, meaning that the player doesn't care if you play from the main view or the playlist view.

One specific bug happening is you will see the "now playing" animation in both the Library view and the Playlist view.

About your very problem, I am not sure what should be the solution UX-side. I will try to see how other players handle this case.

**Comment by a2nt** [comment]
hmm, that's true too, but itunes has an option to add to queue

**Comment by KeitIG** [comment]
There is one too in Museeks, or are you talking about something else?

**Comment by a2nt** [comment]
@KeitIG sorry missed it thx, but would u also like to add an option: "Play next"
