### ISSUE TITLE
[FEATURE] click to tray icon shall toggle player window

### ISSUE THREAD

**Issue by a2nt** [KeitIG/museeks#393]
First click shall show window, if window is shown it shall hide it

**Comment by KeitIG** [comment]
I don't think this is a good idea, the tray is mostly used to give you the play/pause/next/previous features. If I am working in another program, I do not want museeks to pop-up.

On Win32 though, double clicking the tray shows the app, and right-click show the context menu.

https://github.com/KeitIG/museeks/blob/master/src/main-process/tray.js

**Comment by KeitIG** [comment]
Let's move everything to #389
