### ISSUE TITLE
[QUESTION] What about storing JetBrains configuration at git repo?

### ISSUE THREAD

**Issue by a2nt** [KeitIG/museeks#396]
I'm using WebStorm and it stores project configuration at the folder named .idea
Shall I add it to .gitignore or commit it?

**Comment by KeitIG** [comment]
Yeah sure, can you add `.vscode` in `.gitignore` too if it's not already there?

**Comment by KeitIG** [comment]
@a2nt, sorry I was not clear. Can you do this in a separate branch? So we can merge these changes without having to review things that we don't agree on.

**Comment by KeitIG** [comment]
I talked with a few colleagues about this problem, they told me these kind of configuration should be done in your global `.gitignore`, and not in the project's gitignore, which is fair :)
