### ISSUE TITLE
Reduce CPU impact when tracks are playing

### ISSUE THREAD

**Issue by KeitIG** [KeitIG/museeks#402]
Nevermind my earlier tweet, I was kind of wrong. When idle, Museeks has a normal CPU consumption, but it jumps up to 40% when playing museeks, I have a few idea why, and need to investigate.

**Comment by YurySolovyov** [comment]
Obvious advice, but: take a look at profiler?

**Comment by KeitIG** [comment]
Yep indeed. Interesting to see this too: this is a page with just an `<audio>` tag playing.

<img width="285" alt="screen shot 2018-02-22 at 17 19 56" src="https://user-images.githubusercontent.com/1311607/36550088-abc249c0-17f4-11e8-8178-2d83f4cf0b87.png">

**Comment by KeitIG** [comment]
Ok, it appears this little bitch is responsible of a 20% CPU usage alone. I may want to force GPU rendering for the animation.

**Comment by KeitIG** [comment]
Closed by #404
