### ISSUE TITLE
Library is randomly reset 

### ISSUE THREAD

**Issue by KeitIG** [KeitIG/museeks#408]
I have no idea if this is due to an Electron update but my library gets randomly reset after launching the app.

Possible causes: 

- Something happens to the config folder
- Electron update?
- Switch from Electron dev build/real Museeks app

**Comment by YurySolovyov** [comment]
shouldn't this be fixed before/with 0.9?

**Comment by KeitIG** [comment]
I do not have clear steps to reproduce it, this is really weird. It just happened a few times completely randomly.

**Comment by KeitIG** [comment]
Could not reproduce it in some time. Closing it for now.
