### ISSUE TITLE
Improve (really) large libraries handling

### ISSUE THREAD

**Issue by KeitIG** [KeitIG/museeks#414]
Museeks is fine with small and medium libraries. However, there is always a OMGUbuntu! guy to come and say "I have a 6TB library, how would Museeks perform with it?".

- Check any slowdown/bottlenecks:
  - During the scan
  - UI responsiveness in general
- Improve/fix what can be improved/fix

---

Things found so far:

### UI/UX

- [x] Better visual indicator when refreshing the library

On really large libraries (let's say 100K files), you will not see a lot of progress in the footer. Maybe we could add a spinner, an animated progress bar or the count of scanned files.

- [ ] Libraries information/stats

In the settings view, Library tag, we could add more information about the library: the number of files, the total size of it...

---

### Scan

- [x] Check how we could boost up things even more

Other id3 libraries (#371), improve the "get duration" operation...

- [x] Add tracks to the libraries during Library scan

Reports were made of some frustration with big libraries being scanned and no possibility to start playing music right away. Because it could be a costly render/thing, maybe add a bulk of 100/1000 tracks at a time.

--- 

### UI navigation performances

- [x] Improve scroll in TracksList https://github.com/KeitIG/museeks/blob/master/src/ui/components/Shared/TracksList.react.js#L162

Scroll in Trackslist is CPU consuming to keep some basic operations like track selection fast and in O(1). It forces us to split tracks into chunks and to render them. Maybe we could improve things a bit more here, by tracking what is being re-rendered and what is not.

- [x] Library’s `mapStateToProps` https://github.com/KeitIG/museeks/blob/master/src/ui/components/Library/Library.react.js#L104

So we moved the search/sorting logic here because it is simpler to handle that way. There are inconsistencies with how other tracks list are used in the store (playlist are already sorted for example). At every `Library.react` re-render, these "costly" operations are made. Maybe by re-moving things to actions we can solve both perfs and KISS problems. 

- ~[OPEN QUESTION] Improve DB performances: ditch IndexedDB/LinvoDB3 and switch to something else, like Dexie, PouchDB or sqlite?~
_Linvo is fine_

LinvoDB3 is not the fasted when it comes to full-database loading, I would be curious to see how other files-based DB compare.

**Comment by lachlan-00** [comment]
I have ~180k files so i can test this out for you. would you like to follow a process or use certain commands to get information about the load?

**Comment by KeitIG** [comment]
What I would be really interested is how well/bad Museeks performs compared to your usual default player :)

- for the scan performance 
- for the UI responsiveness in general

The first one should be ok I think, the second one is the one I’m the most afraid of.

**Comment by lachlan-00** [comment]
Can do! I have a folder with 20k to test and I'll start with that. Do some timings, etc

**Comment by lachlan-00** [comment]
I started with a test folder with 19,356 mp3 files over nfs.

no slow downs with the interface while adding tracks at all. In fact it was prefect during the whole import. (besides being empty)

Visually the progress bar is the only indication that anything is happening and i suspect that as the file count get larger it would be harder to identify that anything is actually happening.

no pause/reload seems like the library needs to finish completely before saving tracks? does it write to a temp file then merge after?

Scan took 19:41 to complete and initially said 'too bad there are no tracks' until i switched panes back and forth.

quodlibet is much slower to scan but adds files to the library faster. (3 mins file scanning but then adds single files at about 1000 per min so it's similar speed to museeks)

I added the test folder as a second library in rhythmbox (which has to scan and load my 184k DB as well.)
Files started appearing in 25 seconds and were added at about 500 a minute. Rhythmbox would be faster without my primary library but it was a good test to show that rhythmbox will import quickly while under load.

But unlike rhythmbox my library in museeks was near instantly loaded and i was able to move about the interface right away. That's very impressive for any music player!

**Comment by KeitIG** [comment]
> no pause/reload seems like the library needs to finish completely before saving tracks? does it write to a temp file then merge after?

Every tracks is saved to the library when the id3 has finished being parsed, so if the app crashes and you start re-scanning again, all previously saved tracks won't be re-scanned.

> Scan took 19:41 to complete and initially said 'too bad there are no tracks' until i switched panes back and forth.

I had the idea to display tracks once they are added in the database, but it could be REALLY CPU consuming if you stay on the library view. Maybe we could bulk them though, and add 100 tracks at a time, it should not be too hard to implement.

> But unlike rhythmbox my library in museeks was near instantly loaded and i was able to move about the interface right away. That's very impressive for any music player!

Good to know! It will help us to know where we can improve things 👍

**Comment by YurySolovyov** [comment]
We can show added/total count near the progress bar, should be cheap enough to update 1 text node

**Comment by lachlan-00** [comment]
Could the settings page show a library file total?
That would give a visual progress while keeping it out of the library pane.

**Comment by lachlan-00** [comment]
Progress bar works too

**Comment by KeitIG** [comment]
I started to write some issues/potential fixes in the first comment

**Comment by YurySolovyov** [comment]
as a DB option, there is [Dexie](https://github.com/dfahlander/Dexie.js)

**Comment by lachlan-00** [comment]
Just one last update before I go to bed.

Startup with 20k tracks is near instant.

Startup with 71k takes 20-26 secs.

Sync for 70k was about 1hr20

**Comment by lachlan-00** [comment]
Looks like there's an issue once you get large.

I have been scanning my main library for almost a day now after stopping at 71k last night and it still hasn't completed. Stuck at half way by the looks.

I'll keep it going to see what happens but it is suffering somewhere in the process

**Comment by KeitIG** [comment]
Ok, please do not laugh at this one.

We are experimenting with multiple front-end framework at work like Vue, React or Svelte. I am currently concerned by how the `TracksList`'s render method, especially during scrolling for huge libraries.

The main reason we implemented it that way with tiles and all these tricky tricks was to improve the rendering speed: render more often, but in O(1) instead of O(n), n being the number of songs in a library.

With 6000 tracks, with the previous method, a render was done in 100-200ms, which is noticeable by the user and does not feel responsive.

I just tried this Vue component: 

```
<template>
  <div class="page-test">
    <div class="list">
      <div
        v-for="item in items"
        :class="isSelected(item)"
        class="track"
        v-on:click="select(item._id)"
      >
        {{item._id}}
      </div>
    </div>
  </div>
</template>

<script>
  import uniqid from 'uniqid';

  const list = [];

  for (let i = 0; i < 10000; i++) {
    list.push({
      _id: uniqid(),
      index: i,
      text: Math.random(),
    });
  }

  export default {
    data: function() {
      return {
        selected: [],
        items: list,
      };
    },
    methods: {
      isSelected: function(item) {
        return this.selected.includes(item._id) ? 'selected' : null;
      },
      select(_id) {
        if (!this.selected.includes(_id)) this.selected.push(_id);
      }
    }
  }
</script>

<style>
  .page-test {
    max-width: 100%;
    width: 600px;
    margin: auto;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
  }

  .list {
    border: solid 1px lightgrey;
  }

  .track {
    padding: 8px 16px;
  }

  .track:not(:last-child) {
    border-bottom: solid 1px lightgrey;
  }

  .track.selected {
    background: #555;
    color: white;
  }
</style>
```

With 10'000 items, a render is not perceptible: a track is instantly selected. Render starts to be noticeable at 20K/30K items.

I means in this scenario, with no real optimization, Vue is significantly faster for rendering long lists (I suspect it too be more RAM-hungry too, because you have observers everywhere.

This gives me two ideas: 

- Rewrite the whole UI with Vue (I'm joking, but only half-joking)
- See how we could optimize `TracksList` more, I see multiple places we could improve perfs in this huge bloated component.

**Comment by YurySolovyov** [comment]
I know our `TracksList` is kinda home-grown, have you tried other virtualized lists components?

**Comment by YurySolovyov** [comment]
E.g. https://github.com/Flipkart/recyclerlistview

**Comment by KeitIG** [comment]
f0f2cfa519b72df0500505fc3686ee61e1f6af4e Improve library scan performances
38087714c9cb1d5ca523f8855b97a4442a36d187 Reduce the number of UI updates during scans
0e79cf6f807bd7d61fb00c5f3781db8d0672ad64 Add tracks to the library view during scan
9305dbdbfd7640f743791c76961a2d053040a37e Optimize tracks filtering

Museeks will now add tracks to the Library view every 100 file scans 🎉

**Comment by KeitIG** [comment]
I am closing the issue for now, I won't implement the "Library information/stats" now as it may bring database schemes update and the feature does not seems _that_ needed.

Feel free to discuss it if you think the opposite, and I'll re-open it (or will open a separate issue)
