### ISSUE TITLE
Window title switches to "index.html"

### ISSUE THREAD

**Issue by celynwalters** [KeitIG/museeks#419]
When Museeks opens (normally or toggling native frame), the window title is `Museeks`.
Switching tab to playlists or settings will cause it to change to `index.html`.
(Affects the taskbar, and title bar if native frame is enabled)

Tested on 0.9.0, Windows 10.
I couldn't reproduce this in 0.8.1 (x64).
Used fresh 'AppData/Roaming/Museeks' each time.

**Comment by KeitIG** [comment]
Hello!

Thanks for the report, can you share a screenshot and tell me your OS and which binary you used?

**Comment by KeitIG** [comment]
np, I can reproduce it. I will investigate :)
