### ISSUE TITLE
Some input

### ISSUE THREAD

**Issue by lottanbettan** [KeitIG/museeks#423]
Great app! Clean and simple without cloud sync and all that.

On macOS, I'm dreaming of:
* keyboard shortcut to hide window: cmd+H (default in system and 99% of apps).
* monochrome tray icon(s) option (black on light, and white on dark).
* most wanted: hide tray icon option (a lot of mac users really dislike "forced" tray icons).
* a short delay (0.2 sec?) on hoover (volume button and timeline bar), would fix the "flickering" appearance.

I could make the monochrome tray icons if that would help.

**Comment by KeitIG** [comment]
Hello @lottanbettan,

thanks for the feedback!

- Shortcuts: shoudn't be too hard
- Monochrome icon: #259 existing issue :) I may need the help of a designer on this one
- Hide Tray option: I agree with you; maybe we should update the behavior of "minimize to  tray" option
- Flickering: I cannot reproduce it on macOS; can you do a screencast?

**Comment by lottanbettan** [comment]
Hi, thanks for the app!
* I tried to upload 2 *.svg monochrome tray icons (light and dark mode) here on github, probably I messed up though :)
* Minimize to tray is great in Windows, but in macOS it's better to skip the tray icon and just minimize to "dock" (play/pause and prev/next is easy done with the keyboard).
* Flickering: no I can't :) but I can try to explain better... It's not really flickering, but when the pointer is passing by the volume icon and timeline the hoover effect is instant (without delay), which makes it "flicker". It's not a bug though. Compare with github - try to hoover the link #259 and you will see that the hoover popup is delayed maybe 0.4 sec.

**Comment by KeitIG** [comment]
Oh I see, by flickering you mean « when quickly hovering the volume icon with no intention of actually changing it » right? I didn’t think about that and this is a valid point to me.

About the Tray Icon, I kind of agree too with you, I’ll do some research about the behaviors of apps on different OS

**Comment by KeitIG** [comment]
And thank you so much for the icons 🙏 I’ll check them out today!

**Comment by lottanbettan** [comment]
:) yes exactly! you said it with less words and more meaning.
not a problem, tell me if you want the icons to be changed in any way and I'll give it a try.

**Comment by KeitIG** [comment]
I am thinking about purely disabling Tray on macOS since we have the same content in the dock, global shortcuts work great, and it only makes sense on Windows/Ubuntu where hiding the app remove the icon from the dock.

I know some people prefer having options, but I like having opinionated way to do things. When I implemented the Tray, I had no mac. Now I have one, I do not really see its use on this platform.

What do you think @lottanbettan ?

**Comment by lottanbettan** [comment]
100%! 👍

**Comment by lottanbettan** [comment]
I don't really know the culture on GH, should I close the issue when we reached this far? :)

**Comment by lottanbettan** [comment]
hehe sorry, close, open, close

**Comment by lottanbettan** [comment]
I don't really know the culture on GH, should I close the issue when we reached this far? :)

hehe sorry, close, open, close

**Comment by lottanbettan** [comment]
Or I'll just continue to use this thread...

More wishes:
* Make title, artist and genre clickable to filter the clicked "keyword".
One simple(?) solution would be to make searches like "genre:rock" and "artist:beatles" filter that content, and that the click just adds that text to the search bar. Then there is no need for a new navigation button ("go back to full library" button), it's just for the user to clear the search bar. Like this it's also easy for the user to make own custom filters like "song:love".
* Option to disable album covers from the main window - they disturbes the stylish minimalism imho.
* View and edit id3 tags.

**Comment by KeitIG** [comment]
Some of your points were fixed in the 0.9.1 release :)

About: 

Advanced search: https://github.com/KeitIG/museeks/issues/230
ID3 tags: #197

**Comment by lottanbettan** [comment]
Hi again :) Still longing for the tray icon to disappear in macOS :) Pleaaaaaaaase

**Comment by KeitIG** [comment]
Can you open a separate issue for this? It's easier to keep track of things. :)

**Comment by lottanbettan** [comment]
Sure thing! #447 
All the best.
