### ISSUE TITLE
Shuffle bug

### ISSUE THREAD

**Issue by lottanbettan** [KeitIG/museeks#427]
On mac:

If shuffle is ON when music is started: when shuffle is turned OFF the app window turns all white, but music continues.
Doesn't seem to matter if the queue is empty or not.
It's not like this with the repeat function.

All the best!

**Comment by KeitIG** [comment]
Fuck this, again. I thought it was fixed.

I really need to implement unit-tests...

**Comment by lottanbettan** [comment]
Sorry, didn't know this was a sensitive issue :)
Thanks for all your great work, looking forward for upcoming releases.

**Comment by KeitIG** [comment]
I'll try to fix it and release a patch asap
