### ISSUE TITLE
Some m4a files are not added to the library

### ISSUE THREAD

**Issue by brachna** [KeitIG/museeks#438]
Windows 8.1 64bit, Museeks 0.9.3

Some m4a files are not added into the library after folder scan. Example file:
[4. New Track #2 (Live).zip](https://github.com/KeitIG/museeks/files/1907760/4.New.Track.2.Live.zip)

Included file plays perfectly in Clementine and Tomahawk.

**Comment by KeitIG** [comment]
Hello!

I just tried importing the file you just sent, there is a metadata problem obviously (I need to check that out), but the file is imported.

![screen shot 2018-04-13 at 16 57 25](https://user-images.githubusercontent.com/1311607/38742048-c14f39b0-3f3b-11e8-838c-c8bf9769af61.png)

**Comment by KeitIG** [comment]
For the record: 

<img width="762" alt="screen shot 2018-04-13 at 16 59 12" src="https://user-images.githubusercontent.com/1311607/38742138-070f6dc6-3f3c-11e8-9017-c98208cdf0ed.png">

**Comment by KeitIG** [comment]
I fixed the duration problem, and I opened an issue there: https://github.com/Borewit/music-metadata/issues/74, as it is a problem with the library we use to extract id3 tags.

**Comment by KeitIG** [comment]
@brachna can you confirm that the file is added to the library, but without correct id3 tags?

**Comment by brachna** [comment]
I checked and yes, it is added as unknown artist.
It can't be played though.

**Comment by KeitIG** [comment]
Oh really? Can you in settings > advanced > open dev tools, and tell me the error you get in “console”?

Much appreciated 🙏

**Comment by KeitIG** [comment]
Yep this is what I noticed too, I'll investigate on Ubuntu. Thank you for the report o/

**Comment by brachna** [comment]
Thank you for looking into it.

**Comment by KeitIG** [comment]
I still get some errors with some files https://github.com/Borewit/music-metadata/issues/77

**Comment by KeitIG** [comment]
Fixed in 0.9.4 :)
