### ISSUE TITLE
Playlist syncing with Android

### ISSUE THREAD

**Issue by balzabalza** [KeitIG/museeks#439]
Hi,

I have a feature request based on a common scenario:

- Let's say I factory reset my Android phone, for whatever reason. All music files would be canceled.
- My phone has limited storage, and y music library is larger than that so I'm used to select the music I'm more likely to listen to in those days
- What I normally do, is select the album folders I want one by one, and copy them into my phone

So, my request is: why don't create a playlist in Museeks, so that it can be synced to my phone? A bit like iTunes handles iPhones.

Case scenario:

- I create a playlist in Museeks
- I plug my phone into my PC
- I sync (manually, or automatically), that playlist to my phone, in a default folder or in a custom one.

Such a feature is already handled by "Lollypop music player", but it runs on Linux only. I would even economically contribute to such a feature, it would be a step forward to drop iTunes for me, as it became very resource heavy on my PC.

I'm curious to hear what you think about this :)

**Comment by KeitIG** [comment]
Thank you for the feature request, Museeks does not aim to have these kind of features soon (keep it minimal/functional).

I will close it for now.
