### ISSUE TITLE
Can't play songs with character '#' in filename

### ISSUE THREAD

**Issue by brachna** [KeitIG/museeks#443]
Windows 8.1 64bit, Museeks 0.9.4

Related discussion in #438, same file

![error](https://user-images.githubusercontent.com/5756107/39202242-fdbcea02-47f9-11e8-98eb-689183401730.jpg)

**Comment by KeitIG** [comment]
Hello :)

It has been fixed in master, but has not been released yet. I may need to create a patch release just with this fix.

**Comment by KeitIG** [comment]
I'll release the next version soon, sorry for the delay
