### ISSUE TITLE
Error when trying to play ANY song

### ISSUE THREAD

**Issue by wilchak** [KeitIG/museeks#451]
Hi, I just installed Museeks (MacOS 10.13.4) and am having a problem. I added my music (all M4A Apple Lossless files), and when I try to double click to play a song in the main list (everything shows up fine...), I just immediately get the corner error popup "The track file could not be found. It may be due to a file move or an unmounted partition."

Of course, the files are still there (and clicking "Show in file manager" from the context menu works just fine). But none of them can be played. All these files can be played in other applications. The drive itself is a regular HFS+ volume.

Let me know how I can help debug this.
Thanks.

**Comment by KeitIG** [comment]
Hoy! Thank you for the report, is there at special character in the path of your file? `#`, `{` or others?

**Comment by KeitIG** [comment]
Also, could you go in Settings -> Advanced -> Open dev tools and make a screenshot of the "console" tabs?

**Comment by wilchak** [comment]
Nope, no special chars. Screenshot attached.
<img width="1334" alt="no go" src="https://user-images.githubusercontent.com/2185789/41006620-44de5bfc-68f0-11e8-9865-a2544bfc9d32.png">

**Comment by KeitIG** [comment]
Thank you very much, it looks like a bug in the file location resolution. Can you send here the full path of one of those files? So I can reproduce it and submit a patch ASAP :)

Sorry for the inconvenience.

**Comment by wilchak** [comment]
The full path of one of the files is.... /Volumes/RAID/Music/Albrecht
La'Brooy/Albrecht La'Brooy - Tidal River (2018) [WEB-FLAC]/1
Daybreak.m4a

On Wed, Jun 6, 2018, at 3:01 AM, Pierre de la Martinière wrote:
> Thank you very much, it looks like a bug in the file location
> resolution. Can you send here the full path of one of those files? So
> I can reproduce it and submit a patch ASAP :)> Sorry for the inconvenience.


> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].

Links:

  1. https://github.com/KeitIG/museeks/issues/451#issuecomment-394962394

**Comment by KeitIG** [comment]
I added a couple of fixes in the last months, I could not reproduce the bug with this filename/path. Hopefully I will do a new release soon.
