### ISSUE TITLE
a multitude of items that I personal would add if I knew how to and where the developer

### ISSUE THREAD

**Issue by peppersblanket** [KeitIG/museeks#452]
I use Linux mint 18.1, with 16gb ddr3 a i7 4790 and a gtx 970 running with x server
it would be nice to see museeks as a player in Linux in the sound applet, you should make a custom GUI instead of using chromium as a base, that would be nice it would also fix the problem of lag when moving UI around on cinnamon when museeks is open, the affect is the same as chrome and chromium. the problem is fixed when I close to the system tray 
another useful thing would be the ability to see individual albums, I know that you want simplicity but I would find an album list to be more useful than the play list menu
also the ability to see the file type flac, mp3, wav, ect...
I hope that you do not find this request petty thank you for your time

**Comment by KeitIG** [comment]
Hello, thank you for all those ideas :)

For the Linux integration -> https://github.com/KeitIG/museeks/issues/93
For the album view -> #130 

Those two will be done 100% at some point.

Not using Chromium as base is not for today, a lot of features depends on API provided by Electron, moving away from Electron would probably lead to a full rewrite of the app using tools/languages/framework I do not know.

If you have issues with Chrome in general, our hope is to expect these to be fixed upstream by Google or Github. I will investigate as this is the first time I'm hearing qbout this issue.

Finqlly, about seing the file type: I am not sure to see what it brings for the user.

**Comment by igorer88** [comment]
Maybe adding on file's context menu a properties option, would show all properties, including the file type. It helps when we have multiples version of the same song added on the library and we want to delete a specific one. (Happened to me with FLAC files which I converted to mp3)

**Comment by martpie** [comment]
There is already an option to locate a file in your file explorer, I think it covers 99% of the usecases.

**Comment by igorer88** [comment]
But if we're going to integrate metadata editing is something that can be added, is simple and complements the metadata. Some songs can't have their metadata edited (Don't know why) maybe would help if the file type is there.
