### ISSUE TITLE
Symlinks in music directory

### ISSUE THREAD

**Issue by Phenitei** [KeitIG/museeks#58]
It may happen, e.g. using git-annex, that in the music directory are symlinks that point in or out of the music library. It would be nice to be able to ignore symlinks pointing inside|outside the music library. Another option would be to be able to ignore certain directories (the .git in the case of git-annex).

**Comment by KeitIG** [comment]
Waiting for you to test the latest sources to see if the issue stil happens

**Comment by KeitIG** [comment]
Needs investigation as it causes a freeze on some linux distributions. (archlinux apprently) whereas it's working fine on Ubuntu.

**Comment by Phenitei** [comment]
Pulled, rebuilt and all is well. The load is high (~5) but the system takes it well with only a few slowdowns on IO ops (7200RPM HDD). Tried again with ionice and all was rolling perfectly. Closing issue.
Ps: I think the size of my library more than the distribution was causing the problem ;-)
