### ISSUE TITLE
Sort columns in TracksList

### ISSUE THREAD

**Issue by KeitIG** [KeitIG/museeks#62]
This is a to-do thing: we must be able to add/remove/rearrange metatags columns. Not the most urgent thing though.

- [x] asc/desc sort on click

## Sorting algorithms

```
Default: 

const querySort = {
    'loweredMetas.artist': 1,
    'year': 1,
    'loweredMetas.album': 1,
    'disk.no': 1,
    'track.no': 1
};
```

**Comment by dkniffin** [comment]
- [ ] Sort by column on click

**Comment by KeitIG** [comment]
Indeed.

The main difficulty here is sorting. E.g If I filter by year, great, but how tracks with the same year will be sortered then ? Do we need to define how every sorting should behave ?

Like: 

```
Filter by artist: artist -> album -> year -> cd.no
Filter by year: year -> artist -> album -> cd.no

... and so on ...
```

@YurySolovyov Did you encouter these kind of problems with folders sorting with Eion for example ?

**Comment by dkniffin** [comment]
We could add a "type" to each column, like date, string, number, time, etc. Then we'd just have a sorting algorithm for each one.

**Comment by KeitIG** [comment]
I think that's indeed the thing to do. We just have to define the sorting algorythm for every column now .__.

**Comment by YurySolovyov** [comment]
@KeitIG there was (and still is) an issue like "finding a needle in the haystack", where I need to select 1 item in 6k lines and it take a lot fot react to do it.

I'd measured the time it needs to just re-render entire view, which would probably happen on most sorts.

Other things is to try to employ some kind of Virtual Lists that render only the visible items.

**Comment by KeitIG** [comment]
@YurySolovyov You might be interested by: http://blog.atom.io/2015/06/24/rendering-improvements.html

I was more thinking about the sorting algorithms here between rows here

**Comment by YurySolovyov** [comment]
@KeitIG sorting itself is going to be fast compared to the actual rendering. I think.

**Comment by KeitIG** [comment]
I think you don't get what I mean haha. I'm just speaking about sorting files/folders here, imagine you sort by "type", so it sorts all your directory with let say folders first, then files.

Do you have a second sort ? To sort by filename ?

**Comment by YurySolovyov** [comment]
@KeitIG I went simpler way, though it won't work for museeks:
I split folders and files into 2 arrays, sort them separately, and then `.concat` them back.
I do this cause I want folders to always be on top regardless of current sorting.

**Comment by dkniffin** [comment]
[react-datagrid](https://github.com/zippyui/react-datagrid) seems to accomplish what we want. Thoughts?

**Comment by KeitIG** [comment]
No, it lacks all the features of the `TracksList` component

- dynamic loading & rendering
- all events
    - click, contextmenu
    - keys...
- it's not sexy
- it's fun to reinvent the wheel for this kind of things

**Comment by YurySolovyov** [comment]
@KeitIG FWIW last time I looked into `TracksList`, it was pretty scary

**Comment by KeitIG** [comment]
Well, there's a bit maths inside.

**Comment by dkniffin** [comment]
Hmm. I think it does support some of those features, but I looked into it a bit more, and it looks like it's not being very well maintained so I agree we shouldn't use that.

However, are you opposed to using _any_ 3rd party component libraries? It certainly is fun to reinvent sometimes, but it's also a lot of work.

**Comment by KeitIG** [comment]
@dkniffin Ofc

```
    "open-sans-fontface": "1.4.0",
    "react-bootstrap": "0.30.7",
    "react-fontawesome": "1.4.0",
    "react-keybinding-component": "0.4.1",
    "react-redux": "4.4.6",
    "react-router": "3.0.0",
    "react-router-bootstrap": "0.23.1",
    "react-simple-input": "0.3.1",
    "svg-inline-react": "1.0.2",
```

For `TracksList`, it's specific too much, there's absolutely no problem in building a complex component.

**Comment by dkniffin** [comment]
Alright, well to that end, I'm going to refactor TrackList a bit.

**Comment by KeitIG** [comment]
ok, for this one we can start with sorting. Editabnle columns is a bonus that can be done lanter

**Comment by YurySolovyov** [comment]
How are we going to store them? in config or db?

**Comment by KeitIG** [comment]
For sorting, there will be a hashmap for each type of column: 

```
Filter by artist: artist -> album -> year -> cd.no
Filter by year: year -> artist -> album -> cd.no
...
```

So we'll need to agree on these.

Then there will be two options stored in config: 

- sort column
- asc/dsc

and I think the asc/dsc option should only apply on the first parameter, so for "Filter by artist" and "dsc", only the "artist" key would be sorted dsc. The "sub-keys" would be asc.

**Comment by KeitIG** [comment]
```
Default (current)

{
    'loweredMetas.artist': 1,
    'year': 1,
    'loweredMetas.album': 1,
    'disk.no': 1,
    'track.no': 1,
}

-----

Tracks ASC: 

{
    'loweredMetas.title': 1,
    'loweredMetas.artist': 1,
    'year': 1,
    'loweredMetas.album': 1,
    'disk.no': 1,
    'track.no': 1,
}

Tracks DSC: 

{
    'loweredMetas.title': -1,
    'loweredMetas.artist': 1,
    'year': 1,
    'loweredMetas.album': 1,
    'disk.no': 1,
    'track.no': 1,
}

-----

Duration ASC

{
    'duration': 1,
    'loweredMetas.artist': 1,
    'year': 1,
    'loweredMetas.album': 1,
    'disk.no': 1,
    'track.no': 1,
}

Duration DSC

{
    'duration': -1,
    'loweredMetas.artist': 1,
    'year': 1,
    'loweredMetas.album': 1,
    'disk.no': 1,
    'track.no': 1,
}

and so on...

- put the primary key used for sorting first
- add the default sorting options 
- remove its duplicate if needed
```

**Comment by KeitIG** [comment]
This is in progress, last big issue to fix before 0.9 release.

**Comment by KeitIG** [comment]
Going through the whole thing, I do not think it makes any sense to add sorting for playlists.

**Comment by YurySolovyov** [comment]
Why not?

**Comment by KeitIG** [comment]
Done in #411

**Comment by ldexterldesign** [comment]
Screen cast: https://www.dropbox.com/s/zm93w28rsqsvj1k/foo.webm?dl=0

Hmm, primary sorting by album isn't secondary sorting by track - bug?:

If yes then happy to create a new issue
If no then makes sense to reopen this issue
If related to another TODO then probably best to link it as I'm sure others will come to find this

Yours hopefully

PS files have track # ID3 tags:

![Screenshot 2020-02-06 at 03 42 10](https://user-images.githubusercontent.com/1715809/73902249-6fb9dc80-4895-11ea-8c70-a4486c441139.png)

**Comment by martpie** [comment]
You can see the order here: https://github.com/martpie/museeks/blob/master/src/ui/constants/sort-orders.ts

Feel free to open an issue if you disagree with one :) (possible I made a mistake too)

**Comment by ldexterldesign** [comment]
I see, so the reason [t]his isn't working is because track numbers aren't implemented (as columns) yet?

Cheers

t:
> Primary sorting by album isn't secondary sorting by track - bug?:

**Comment by martpie** [comment]
It should: `[['loweredMetas.album', parseArtist, 'year', 'disk.no', 'track.no']`

Can you open an issue with screenshots and files to reproduce the issue?

**Comment by ldexterldesign** [comment]
Hi @martpie,

FYI will open a new issue in due course if I suffer the same issue with the next batch of imported music

Aside, is there a reason a track number column isn't available?

Tonight I have an album where a couple of tracks have inconsistent artist tags which throws out the album's natural play order and I'm unable to fix it because there's no track number column

Hope to hear back

Sincerely

**Comment by martpie** [comment]
> Tonight I have an album where a couple of tracks have inconsistent artist tags which throws out the album's natural play order and I'm unable to fix it because there's no track number column

Yep, this is a limitation of the current view, hopefully #130 will help fix that :)

> Aside, is there a reason a track number column isn't available?

If track number was available, all the tracks "1" would be grouped together, then all the "2", etc. That is why it makes no sense to display (for now) a "tracks number" column

**Comment by ldexterldesign** [comment]
Search/filter by album (see screen shot above) then sort by track number would allow me to fix this use case so, if #130 is bottlenecking this then, I would suggest a track number column would make sense now

**Comment by martpie** [comment]
Cf #401 then I believe :)

**Comment by ldexterldesign** [comment]
> Can you open an issue with screenshots and files to reproduce the issue?

> I will open a new issue in due course if I suffer the same issue with the next batch of imported music

@martpie still suffering [this] issue - would you like me to create a new issue or do you think #130 and/or #401 will fix this?

Sincerely

[this]: https://github.com/martpie/museeks/issues/62#issuecomment-582714240

**Comment by ldexterldesign** [comment]
BUMP

**Comment by ldexterldesign** [comment]
BUMP
