### ISSUE TITLE
Bug with the shuffle button

### ISSUE THREAD

**Issue by timozattol** [KeitIG/museeks#67]
When I press the shuffle button (to activate the shuffle), the interface shows as if a random next track is played (the sound icon changes to a music, and the track name & time remaining changes to that music). Weird...  But the music doesn't really change, as expected it stays on the same track.

Also, if I press shuffle again (to deactivate shuffle), it does the same weird trick but with the first music (music in place "zero"). If I press again (to reactivate shuffle), same trick with music in place "one". I think there is a weird handling of the value of the button (enabled / disabled), which might be assigned to the "current playing track" of the interface at some point.

I can show you / rephrase if it is too confuse!

GREAT WORK BTW the interface is amazing, and everything else works great :heart:

**Comment by timozattol** [comment]
Currently on Ubuntu 14.04, on the .zip you gave me, seems to be v0.36.2.

**Comment by KeitIG** [comment]
Reproduced it. Thanks for the report Tim ;)

**Comment by KeitIG** [comment]
Problem with `playlistCursor` update and backup in `AppStore`, need investigation.

**Comment by KeitIG** [comment]
All done, still a small problem when there's a rollback from a selectAndPlay + shuffle, but it's not a big deal for the moment.
