### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by timozattol** [KeitIG/museeks#68]
Here are a bunch of suggestions I have, feel free to throw some away and open specific issues for the ones that seem relevant. Tell me if something is unclear :)

* Make it more clear that the top left cross closes the program
* Pressing the sound icon mutes / unmutes sound
* Small player feature (only the top bar, with reduced width for example)
* Listen to play/pause next/previous track buttons in Ubuntu (you know, those shortcuts on the keyboard that control the music in your default player). Unfortunately I just spent 10 minutes looking for how to do that, didn't find anything. Tell me if you find how... Maybe do the same for other supported OS
* Library button and settings button could stay selected / gray when you are in the corresponding panel. Meaning if you're in the settings panel, the setting button should be gray. If you're in the library panel, the library button should be gray. As if they were "tabs".
* Maybe make those panel buttons a little bit larger? They are core buttons to navigate in the program, and there are only two of them so they don't use much space. On the other hand I like their square shape now...
* Very small detail: the "repeat once" icon seems to have a different size than the "repeat" icon, so it glitches up somethink like 2px when you activate it. Maybe you could add a few pixels to one, or change the way of centering them so that they "coincide"

**Comment by KeitIG** [comment]
A few things:
- Small player: could be great, but later, there are more important things to do for the moment. Anyway, if there are more asks for that, I'll consider it.
- About the Ubuntu integration, I have no idea how to do this, but it'd be a big plus.

I created specific issues for the other ideas, as they are great indeed.
