### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by KeitIG** [KeitIG/museeks#69]
As shown by @timozattol, minor UI improvements could be done (#68)

- [ ] Repeat icons consistency
- [x] Navigation buttons should have an `active` state
- [x] Improve the close window button
- [x] `btn-default` focus/active styling using dark theme
- [x] Don't show `BrowserWindow` while not loaded
- [x] Bring notifications back for some common errors

**Comment by timozattol** [comment]
:+1:

**Comment by timozattol** [comment]
For the repeat icons, you can open those two in different tabs and see that they are not "aligned" vertically

* https://github.com/KeitIG/museeks/blob/master/src/images/icons/player-repeat-one.svg
* https://github.com/KeitIG/museeks/blob/master/src/images/icons/player-repeat.svg

But it's a very small detail

**Comment by KeitIG** [comment]
Thanks to @Suriteka, we can close this :)
