### ISSUE TITLE
Add install README

### ISSUE THREAD

**Issue by cpursley** [KeitIG/museeks#7]
This project looks great. If you have a chance, do you mind adding installation instructions?

**Comment by KeitIG** [comment]
Hi !

Quite surprised (in a good way) how you find this repo. I need to finish a couple of things (that will be done this week) before building binaries. What OS do you use ?

**Comment by cpursley** [comment]
I'm on Mac OS X at the moment. Thanks.

**Comment by KeitIG** [comment]
Hi again, sorry for the wait, I'm fixing some wrong and deep initial features design.  

I added, an installation to the README.md. You can now run it for fun.

The major bug you will encounter is that you must restart the app to display tracks in the library view once your library is refreshed.

You can close the debug console without worrying too.

**Comment by KeitIG** [comment]
Auto refresh is now fixed.
