### ISSUE TITLE
Better system integration on Windows

### ISSUE THREAD

**Issue by KeitIG** [KeitIG/museeks#73]
For example, with `globalShortcuts`, OS X users can play/pause/previous/formard using their keyboard shortcuts.

In the same way of thinking, there's something that could be done on Ubuntu and Windows I guess, and it'd be great.

- Ubuntu/Gnome: show player controls in music indicator
- Windows: show player controls when hovering Museeks on the taskbar

I'm ok with doing shell operations for that if needed, Electron does not support this natively.

helpers:
https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer
https://msdn.microsoft.com/en-us/library/windows/desktop/dd564016(v=vs.85).aspx

**Comment by YurySolovyov** [comment]
>Windows: show player controls when hovering Museeks on the taskbar

Actually, [it is possible](https://github.com/electron/electron/blob/master/docs/tutorial/desktop-environment-integration.md#thumbnail-toolbars)

**Comment by KeitIG** [comment]
Greaaaat ! Thanks for the information @YurySolovyov

**Comment by KeitIG** [comment]
I'm splitting the tasks for Windows and Ubuntu

**Comment by YurySolovyov** [comment]
With #107 merged, it should be a easier now, will take a look.

**Comment by KeitIG** [comment]
Thanks, don't hesitate to try that with empty icons for now.

**Comment by YurySolovyov** [comment]
Related: https://github.com/electron/electron/issues/2623

**Comment by YurySolovyov** [comment]
We might also want https://github.com/electron/electron/pull/6497

**Comment by YurySolovyov** [comment]
We also might want to do https://github.com/electron/electron/pull/6768 when it is out

**Comment by KeitIG** [comment]
Let's discuss it in a new issue if you see no inconvenience.
