### ISSUE TITLE
Fast scroll in TracksList

### ISSUE THREAD

**Issue by KeitIG** [KeitIG/museeks#79]
With big libraries, it's hard to scroll down due to the small scrollbar. We have to find a way to scroll quickly to W for example.

**Comment by YurySolovyov** [comment]
We might use fuzzy search and jump to best match on key press. Though this might require some tweaking, because it is not ambiguous what "W" means in different places. Or we can just hardcode it to match track titles only.

**Comment by KeitIG** [comment]
That's a nice idea too. I was more thinking about a custom scrollbar, or a fixed div with all letter (A, B, C...) and clicking on a letter would bring you there (like in the old Androïd phones)

I still don't know how it would work with the dynamic loading there is on TracksList.

**Comment by KeitIG** [comment]
@Phenitei sugested something nice: instead of filtering with the search input, we could add an option to "go to" instead of filtering. Don't really know how to integrate this with Flux, but sounds like a good workaround ftm.

**Comment by YurySolovyov** [comment]
As a follow-up to fuzzy search idea, I think it can be tuned to favor matches from the beginning, so that it closer to fixed letters thing you described

**Comment by KeitIG** [comment]
damn, it was fixed a long time ago.
