### ISSUE TITLE
Notification would not disappear

### ISSUE THREAD

**Issue by KeitIG** [KeitIG/museeks#8]
**Only occurs when using ReactCSSTransitionGroup to animate notifications**

After triggering some notifications, I get this warning for an unknown reason. When caught, a notification does not disappear.

There must be a problem in `alert.js`, they react keys seem correct.

```Warning: transition(): tried to perform an animation without an animationend or transitionend event after timeout (5000ms). You should either disable this transition in JS or add a CSS animation/transition.```

**Comment by mrzmyr** [comment]
How about using native notifications ?

**Comment by KeitIG** [comment]
I'd prefer not. Notifications are not that important and should not be displayed outside the player window.

Moreover, notifications do work on OSx, sometimes on Linux, but not on Windows.
see https://github.com/atom/electron/issues/2421

**Comment by KeitIG** [comment]
Notifications are gone for the moment.
