### ISSUE TITLE
Get and set up an icon for the app

### ISSUE THREAD

**Issue by KeitIG** [KeitIG/museeks#81]
Got a designer working on it, here are the first outputs:

![icons](https://cloud.githubusercontent.com/assets/1311607/14090522/37d9d06a-f53b-11e5-9b93-82c36f7cb401.jpg)

**Comment by KeitIG** [comment]
poke @mrzmyr @timozattol @Suriteka, what are your prefs/thoughts guys ? :)

**Comment by timozattol** [comment]
All the ones on the left are nice I think! Else third line first column (of the round ones) (the first one with waves) is really cool. I also like a lot the big one on the right with bars on the bottom, but I think I prefer when the bars are more clustered: second line third column (of the round ones)

Nice design!!

**Comment by KeitIG** [comment]
Just to leave my opinion too, I really like the second row of the rounded ones, particularly the third one (the play symbol making a "M")

**Comment by timozattol** [comment]
@KeitIG do you mean "column"? I also like second column - third row, play symbol with a "M" :+1:

**Comment by KeitIG** [comment]
Yep column, my bad :3

**Comment by mrzmyr** [comment]
I'd definitely raise my hand for the third column. Especially the gray ones.

**Comment by timozattol** [comment]
Seems like everyone likes different stuff, I think at this point it's going to be a matter of taste @KeitIG. Honestly they are all great!

Having the "M" of Museeks somewhere in the icon makes it probably easier to print in someone's mind, so maybe try to focus on those on the right

**Comment by KeitIG** [comment]
Well, I guess we all agree the best icons are those on the second and third columns of the rounded ones (the center group) + the propositions on the right, just waiting for Jonathan's thoughts.

Btw, Joachim's favourites are in the center group: the first in the second colomn and the first in the third one.

**Comment by Suriteka** [comment]
I love the grey one too.
They're all great. But I love this one. 
But yes, if there is the "M" somewhere in the logo, that's better. 

<img width="294" alt="capture d ecran 2016-03-29 a 12 14 20" src="https://cloud.githubusercontent.com/assets/5160323/14104851/d7ef9762-f5a7-11e5-87a3-1d66bc61840c.png">

**Comment by mrzmyr** [comment]
agree with @Suriteka

**Comment by timozattol** [comment]
Same here. If you choose this one, I would suggest making the bars less linear on the left. It seems like they follow a line, I'd find it cooler if they were more "disturbed" like on the right part (matter of taste, linear could be what you want).

**Comment by timozattol** [comment]
Something like that
![museeks](https://cloud.githubusercontent.com/assets/7280428/14106611/b0fcb1de-f5b2-11e5-9f7a-3a14ec8b3a90.png)

**Comment by KeitIG** [comment]
And between the thin line or a bold one, what are your prefs ?

**Comment by timozattol** [comment]
@KeitIG The "bold" one for me. The other one is too thin I think

**Comment by Suriteka** [comment]
I agree with @timozattol , the bold lines are better. It's more clear for the users (Retina Display, ...).

**Comment by KeitIG** [comment]
Thanks for your feedback everyone. I asked the designer some modifications:

- My favourite is this one, I asked her to make a bolder line
![mabstract](https://cloud.githubusercontent.com/assets/1311607/14107414/4f06a3c6-f5b8-11e5-88c6-838602b5d3d8.png)

- Same for this one
![mplein](https://cloud.githubusercontent.com/assets/1311607/14107415/4f07790e-f5b8-11e5-860a-a15dd824afd5.png)

- And I asked for a less linear progression for this one:
![lines](https://cloud.githubusercontent.com/assets/1311607/14107413/4f0272d8-f5b8-11e5-8dcd-40a1a976fa5f.png)

**Comment by KeitIG** [comment]
Hi guys, here are the latest versions

![museekslogov2-03](https://cloud.githubusercontent.com/assets/1311607/14229282/540bbf70-f930-11e5-9064-a0a52dbcaa3e.jpg)

**Comment by mrzmyr** [comment]
3rd row 👍🏼

**Comment by KeitIG** [comment]
Which one in particular ?

**Comment by Suriteka** [comment]
These 2 are just cool.
1pt for the second row :+1: 
<img width="269" alt="capture d ecran 2016-04-03 a 12 09 45" src="https://cloud.githubusercontent.com/assets/5160323/14231907/1e493830-f995-11e5-8eb0-d1d83758aff9.png">
<img width="258" alt="capture d ecran 2016-04-03 a 12 09 50" src="https://cloud.githubusercontent.com/assets/5160323/14231906/1e48fc62-f995-11e5-92bb-c983b045b3e6.png">

**Comment by timozattol** [comment]
Are you all speaking about *columns*? 

I'm for these two:

![logo](https://cloud.githubusercontent.com/assets/7280428/14232088/b67785ec-f99c-11e5-8cde-79ebfb6bb824.jpg)

I like the boldest borders for the first, and I like how the bars progress in the second

**Comment by KeitIG** [comment]
In the last column, I like the second one because you can see the "M" better than the others

**Comment by KeitIG** [comment]
@timozattol @Suriteka For the second row, did you choose the 0.8pt or the 1pt version ?

**Comment by Suriteka** [comment]
I choose the 1pt version.

**Comment by KeitIG** [comment]
Thanks everyone for your feedbacks, last things to do are exports and implementation. Should be done soon. Reporting playlists features to 0.5 as it should take a bit longer than expected.

http://electron.atom.io/docs/v0.37.3/api/native-image/
http://electron.atom.io/docs/v0.37.3/api/browser-window/#new-browserwindowoptions
https://github.com/electron-userland/electron-packager#programmatic-api

**Comment by KeitIG** [comment]
All done. Experiencing some blurry icons with some old Ubuntu versions, but it must related to Electron.
