### ISSUE TITLE
Light cover support

### ISSUE THREAD

**Issue by KeitIG** [KeitIG/museeks#86]
## What

Add the album cover thumbnail in the header while playing music.

## How

- [x] Get cover from `musicmetadata` for file formats supporting it (`picture : [ { format : 'jpg', data : <Buffer> } ],`)
- [x] Define how to store it: create a file ? Link the file to the track with a collection ?
- [x] Get a "no-cover" fallback image
- [x] Front-end

**Comment by YurySolovyov** [comment]
Spotify seems to have some nice [search API](https://developer.spotify.com/web-api/search-item/)

**Comment by KeitIG** [comment]
`musicmetadata` gives you a cover in base64 or sth (so it uses the file metadata, it's not the most accurate, but I pref that instead of an online search).

BUT, a button in the admin "fetch covers online and update my files metadata" could be a really great feature. I'm keeping that in mind.

**Comment by YurySolovyov** [comment]
Sure, if files contain embedded covers, we should use them first, and then use online API as fallback.
So chain liiks like this: `file -> cover in folder -> online API`

**Comment by KeitIG** [comment]
Adding that to 1.0 milestone.

**Comment by KeitIG** [comment]
Reprioritazing it. musicmetadata has a cover support. It'll be light but sufficient for now. I edited the first post, as it's not that straightforward.

**Comment by KeitIG** [comment]
@YurySolovyov What would be your thought about this implementation ? Keep the image in database (read from the metadata, convert it in base 64 or whatever), or write the image on disk and do a link track -> file ?

The second solution is a bit more clean, but we can face a lot more problems too.

**Comment by YurySolovyov** [comment]
Depends on how we search and get the actual image.
How do you like the idea of running express server on main process that handles requests to covers and does the actual cover search / extraction?
Like I did for [`ffmpeg experiment`](https://github.com/YurySolovyov/museeks/tree/ffmpeg)
This way we can transparently add searching for covers in internet services keeping front-end unchanged.

**Comment by KeitIG** [comment]
This user-story is just for fetching covers currently in the id3 tags given by `musicmetadata`. Online fetching may come later. If the picture does not exist, a "by-default.jpg" is displayed.

The question is more: "how to store them ?"

**Comment by YurySolovyov** [comment]
@KeitIG base64 in db is fine by me.

**Comment by YurySolovyov** [comment]
TBH, I'd still done it via separate server, even though this story is about very basic cover support, I want this to be scalable from the beginning

**Comment by KeitIG** [comment]
First draft. The cover will be bigger in the final version.

![capture du 2016-08-23 14 47 03](https://cloud.githubusercontent.com/assets/1311607/17892314/fb837e2a-6940-11e6-8f47-75da473d5b11.png)

**Comment by YurySolovyov** [comment]
I wonder if making progressbar full-width and moving it down would release some space tor cover...

**Comment by KeitIG** [comment]
I slightly increased cover size. (it's not sexy when full-height). I'll investigate for a no-cover fallback tonight.

About the progressbar, "à la iTunes 12" is an option indeed.

![capture du 2016-08-23 15 10 36](https://cloud.githubusercontent.com/assets/1311607/17892894/c8237f78-6943-11e6-9642-f2499329cd9d.png)

**Comment by Suriteka** [comment]
I'll see if I can do something about the UX/UI Research for the cover.
