### ISSUE TITLE
I can't compile it from the source code 

### ISSUE THREAD

**Issue by gitmeteor** [KeitIG/museeks#89]
after I run the npm run compile, what should I do ?

**Comment by KeitIG** [comment]
Hello there !

- Download Electron first
- Fork Museeks
- `git clone [the repo url]` in the `resources/app` path in Electron folder
- `bower install && npm install && npm run compile` should do the trick

don't forget to install bower with `npm install -g bower`

Tell me if you encouter any error

**Comment by KeitIG** [comment]
Hey @gitmeteor, have you managed to get it working ?

**Comment by gitmeteor** [comment]
yes thank you very much
