### ISSUE TITLE
Set playback speed

### ISSUE THREAD

**Issue by dawsonbotsford** [KeitIG/museeks#91]
It does not appear that the playback speed can be changed. Can you create this control? My use case is to listen to mp3 files at 1.5 speed. Having more granular options would be critical though, if this feature is implemented.

**Comment by KeitIG** [comment]
Hi ! 

This is totally possible with the current Audio implementation. This shouldn't be too hard and this is a nice feature, I'll try to do that ASAP.

**Comment by KeitIG** [comment]
- [ ] Add an `Audio` tab in ``Settings`
- [ ] Add an `ìnput[type=number]` in it
- [ ] Save conf on input keydown after a delay
- [ ] Implement this double in the player

**Comment by KeitIG** [comment]
@dawsonbotsford lucky you I'm on holiday. I pushed a ratePlayback option in the settings. Before drafting a new release, I'd like to know if it works well enough for you or if you have any other thoughts.

(you'll need to compile all of that manually, if you can't, I can send you a compiled version of it, just tell me your platform + 32 or 64bits ?)

**Comment by dawsonbotsford** [comment]
I'll try the compilation today ~6 hours from now. Busy for now. Thanks!

**Comment by KeitIG** [comment]
Will be released in Museeks 0.5.0 tonight.
